### DISCUSSION TITLE
Inference Graph API variation proposal

### DISCUSSION THREAD

**Discussion by njhill** [kubeflow/kfserving#2170] [Ideas]
This is a rough proposal for a variation on the current Inference Graph API design in PR https://github.com/kserve/kserve/pull/1910.

Observations related to current design:
1. There seems to be an unnecessary difference between how "service" and "node" invocations are handled
2. It's a bit restrictive in terms of the kinds of composite graphs that can be specified
3. I wonder whether the explicit "router types" are really necessary and if it would be more flexible to frame things in terms of general control flow

I think 1 and 2 could be solved by treating services and nodes as equivalent (each is just a "function" within the flow with input and output). For 3 I was thinking a simpler generic inference node could suffice, which could be easily utilized for any of the existing types.

- Each node is just a list of steps. By default these are processed sequentially, with output from one step forming input to the next.
- Each step points to either a service or a node (allowing arbitrary composition/nesting)
- Steps include an optional condition which controls whether that step is included or skipped, like the existing conditions
- Steps include a `parallel` flag controlling whether they should run in parallel with the prior step(s). The default output of a sequence of parallel steps is similar to the ensemble aggregation already done
```go
type InferenceGraphSpec struct {
	Nodes map[string]InferenceRouter
}

type InferenceRouter struct {
	// Steps are processed in sequence
	Steps []InferenceStep
}

// At most one field can be set
type InferenceTarget struct {
	// The node to execute for this step
	// +optional
	NodeName string `json:"nodeName,omitempty"`

	// The service to execute for this step
        // +optional
	ServiceName string `json:"serviceName,omitempty"`

	// InferenceService URL, mutually exclusive with Service
	// +optional
	ServiceUrl string `json:"serviceUrl,omitempty"`
}

type InferenceStep struct {
	// Unique name for the step within this node
	// +optional
	StepName string `json:"name"`

	// Template of data to pass to this step's target
	// $input input to node
	// $output[stepName].predictions using output from prior step stepName
	// If omitted, output from the prior processed step(s) is used
	// +optional
	InputData string `json:"inputData,omitempty"`

	// Node or service used to process this step
	InferenceTarget `json:",inline"`

	// Condition which must hold for this step to be processed
	// +optional
	Condition string `json:"condition,omitempty"`

	// If true, step is skipped if a step in a prior
	// sequence of conditional steps was processed
	// +optional
	Else bool `json:"else,omitempty"`

	// If true, step is processed in parallel with prior step
	// +optional
	Parallel bool `json:"parallel,omitempty"`
}
```
The simple examples would look pretty similar:
```yaml
# sequence case
root:
  - serviceName: isvc1
  - serviceName: isvc2
```

```yaml
# switch case
root:
  - serviceName: isvc1
    condition: "{.target == \"blue\"}"
  - serviceName: isvc2
    else: true
```

```yaml
# ensemble case
root:
  - serviceName: isvc1
  - serviceName: isvc2
    parallel: true
```
Splitter with weights could be handled as if/else condition, or we could add some extra convenience syntax:
```yaml
# splitter case (here random100 is random val in [0,99] scoped to the node)
root:
  - serviceName: isvc1
    condition: "{random100 < 20}"  # weight 20
  - serviceName: isvc2
    else: true
    condition: "{random100 < 50}"  # weight 30
  - serviceName: isvc3
    else: true  # weight 50
```
A nice thing about this approach is that many graphs can be expressed as a single node, e.g. simple sequence/pipelines and even if they include conditional or ensemble steps. But more complex nested graphs with sub-pipelines are also possible and straightforward to describe. I'll add a couple more examples soon.

**Comment by yuzisun** [comment]
Hi @njhill, thanks for the ideas! 
* For 1 and 2 I have incorporated your suggestion to define the step to either point to a service or a node on the PR, yes this way it allows arbitrary composition. I changed the "Single" type now to "Sequence" so the steps are now chained together by default, I think it is now equivalent to what you have proposed here.
* For 3 I think it is still worth having the explicit router type as in future we may want to implement out of the box multi-arm bandit or ensemble algorithm. That was part of the original design goal to implement inference specific routing graph instead of being a general service graph, what do you think?

**Reply by njhill** [reply]
Thanks @yuzisun I think it looks much better with the service/node unification and sequence type.

I know what you mean about it making sense to keep it domain specific, but as it stands the "types" really just correspond to control flow variations, and I guess you could have pretty arbitrary graph shapes for different inference pipelines. Since the step definitions are shared between the types, it's potentially confusing that some fields only apply for some router types. For example maybe we could at least eliminate the switch type and just have the condition field work in any type (just controlling whether or not the step in question is skipped). I guess the only thing switch gives you over sequence is validation that only one of the conditions triggers.

I was thinking OOTB ensemble algs might be added as special "built-in" InferenceTarget types (i.e. alternative to service/node). So something like:
```yaml
root:
  routerType: sequence
  routes:
    - stepName: preproc
      serviceName: featureExtractor
    - stepName: fan-out
      nodeName: parallel
    - stepName: fan-in
      combinerName: maxConfidence
parallel:
   routerType: ensemble
   routes:
     - stepName: firstModel
       serviceName: isvc1
     - stepName: secondModel
       serviceName: isvc2
     - stepName: thirdModel
       serviceName: isvc3
```
