### DISCUSSION TITLE
Propagate headers to all steps in inference graphs

### DISCUSSION THREAD

**Discussion by rachitchauhan43** [kubeflow/kfserving#2313] [Ideas]
There are 2 approaches to roll-out this feature:

### Approach 1 : 
We make this feature opt-in at per Inference Graph(IG) level, 
For doing so, we would need an extra field in IG KIND itself that can dictate whether for that instance of IG the propagation should happen or not. 

For Example:
A field like `allowHeadersPropagation: true`.

```
apiVersion: "serving.kserve.io/v1alpha1"
kind: InferenceGraph
metadata:
 name: model-switch
spec:
 allowHeadersPropagation: true
 nodes:
   root:
     routerType: Switch
     steps:
     - serviceName: qbo-in
       condition: "[@this].#(country_code==IN)"
     - serviceName: qbo-us
       condition: "[@this].#(country_code==US)"
```

OR,

### Approach 2 : 
Other approach is, we make this feature opt-in at IG’s KIND level
For achieving this, we can create a totally new config map “inferencegraph-config” (just like “inferenceservice-config”) with key `allowHeadersPropagation` that can have values true or false.

```
apiVersion: v1
data:
  allowHeadersPropagation: "true"
kind: ConfigMap
metadata:
  name: inferencegraph-config
  namespace: kserve
```

This discussion is to finalize which approach should be taken from the above ones.
