### DISCUSSION TITLE
Connect InferenceServices deployed on different kubernetes clusters

### DISCUSSION THREAD

**Discussion by rajeshdhanda** [kubeflow/kfserving#2445] [General]
I want to connect **InferenceService_1** in kubernetes cluster ( **region_1** )  to **InferenceService_2** in kubernetes cluster ( **region_2** ). Facing the same issue for inferenceservice deployed in model mesh. Couldn't find anything related to this in docs.

Thanks.

**Comment by yuzisun** [comment]
@rajeshdhanda Can you elaborate more on what "connect" means here?

**Reply by rajeshdhanda** [reply]
Hi @yuzisun 
1st inferenceService use 2nd inferenceService as **predictor_host**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: damage-detection
  annotations:
    autoscaling.knative.dev/scaleDownDelay: '60s'
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
spec:
  predictor:
    nodeSelector:
      cloud.google.com/gke-nodepool: default-pool
    containers:
      - name: kfserving-container
        image: gcr_path_here
        imagePullPolicy: IfNotPresent
        args:
          - --predictor_host=triton-damage-predictor-default.kfserving-triton
```
2nd inferenceService
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "triton-damage"
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
    autoscaling.knative.dev/scaleDownDelay: '1200s'
spec:
  predictor:
    minReplicas: 0
    nodeSelector:
      cloud.google.com/gke-nodepool: gpu-pool
    triton:
      ports:
        - containerPort: 9000
          name: h2c
          protocol: TCP
      storageUri: gcs_model_repo
      image: custom_triton_gcr_path
      imagePullPolicy: IfNotPresent
```
Here 1st inferenceService calls 2nd inferenceService on request. 
due to some contrains and gpu resource availbility, need to put 1st and some other similar inferenceServices in region_1 and 2nd inferenceServices in region_2 in a gpu-pool with `minReplicas: 0`.  
wanted to know, can i achieve such kind of inferenceServices connectivity in gke-clusters in different regions. ( have same doubt for inferenceServices running in model-mesh ) 

Thanks !
