### DISCUSSION TITLE
How to include a new predictor(Serving Runtime) in KServe?

### DISCUSSION THREAD

**Discussion by sindhuvahinis** [kubeflow/kfserving#2450] [Q&A]
/kind bug

**What steps did you take and what happened:**
This is in reference with this issue. [https://github.com/kserve/kserve/issues/2370](https://github.com/kserve/kserve/issues/2370) We introduced a new yaml runtime in this folder [https://github.com/kserve/kserve/tree/master/config/runtimes](https://github.com/kserve/kserve/tree/master/config/runtimes
). 

When we try to do a smoke test, we get this error. 
```
error: error validating "djlserving-example.yaml": error validating data: ValidationError(InferenceService.spec.predictor): unknown field "djl-serving" in io.kserve.serving.v1beta1.InferenceService.spec.predictor; if you choose to ignore these errors, turn validation off with --validate=false
```

Do we need to add something predictor.go? 

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@sindhuvahinis can you show the yaml you deployed with KServe ?

**Comment by sindhuvahinis** [comment]
@yuzisun 

In config/runtimes/kserve-djlserving.yaml

```
apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-djlserving
spec:
  supportedModelFormats:
    - name: pytorch
      version: "1"
      autoSelect: no
    - name: tensorflow
      version: "1"
      autoSelect: no
    - name: mxnet

    # need to add another four
  protocolVersions:
    - v2
  containers:
    - name: kserve-container
      image: kserve-djlserving:replace
      args:
        - --models={{.Name}}
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
        limits:
          cpu: "1"
          memory: 2G
```

In kustomization.yaml
```
  - name: kserve-djlserving
    newName: docker.io/deepjavalibrary/djl-serving
    newTag: latest

```

**Comment by yuzisun** [comment]
@sindhuvahinis How about the example yaml for the actual InferenceService?

**Comment by sindhuvahinis** [comment]
@yuzisun  Sure. 

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "djl-serving-model"
spec:
  predictor:
    kserve-djlserving:
      storageUri: https://resources.djl.ai/demo/mxnet/resnet18_v1.zip
```

**Comment by sindhuvahinis** [comment]
@yuzisun Any update on this? Do we need to change anything else?

**Comment by yuzisun** [comment]
@sindhuvahinis that's the old hard coded way which we no longer support adding new serving runtimes. You should switch to use the new model format spec as we introduce serving runtimes.
https://kserve.github.io/website/0.9/modelserving/servingruntimes/#explicit-specify-a-runtime

**Comment by yuzisun** [comment]
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: djl-serving-model
spec:
  predictor:
    model:
      modelFormat:
        name: mxnet
      storageUri: https://resources.djl.ai/demo/mxnet/resnet18_v1.zip
      runtime: kserve-djlserving
```

**Comment by sindhuvahinis** [comment]
@yuzisun  Thank you for this. We were able to create an InferenceService. but it was not successful. 
We get this error when describing inferenceservice. 

```
Status:
  Components:
    Predictor:
      Latest Created Revision:  djl-serving-model-predictor-default-00001
  Conditions:
    Last Transition Time:  2022-09-30T15:48:56Z
    Message:               Revision "djl-serving-model-predictor-default-00001" failed with message: Unable to fetch image "djlserving:replace": failed to resolve image to digest: HEAD https://index.docker.io/v2/library/djlserving/manifests/replace: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details).
```

**Comment by sindhuvahinis** [comment]
@yuzisun 

Logs of our make command

```
make deploy-dev-djlserving
./hack/model_server_patch_dev.sh djlserving docker.io/deepjavalibrary/djl-serving:latest
kustomize build config/overlays/dev-image-config | kubectl apply -f -
namespace/kserve unchanged
customresourcedefinition.apiextensions.k8s.io/clusterservingruntimes.serving.kserve.io configured
customresourcedefinition.apiextensions.k8s.io/inferencegraphs.serving.kserve.io configured
customresourcedefinition.apiextensions.k8s.io/inferenceservices.serving.kserve.io configured
customresourcedefinition.apiextensions.k8s.io/servingruntimes.serving.kserve.io configured
customresourcedefinition.apiextensions.k8s.io/trainedmodels.serving.kserve.io configured
serviceaccount/kserve-controller-manager unchanged
role.rbac.authorization.k8s.io/kserve-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/kserve-manager-role configured
clusterrole.rbac.authorization.k8s.io/kserve-proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/kserve-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/kserve-manager-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/kserve-proxy-rolebinding unchanged
configmap/inferenceservice-config unchanged
configmap/kserve-config unchanged
secret/kserve-webhook-server-secret unchanged
service/kserve-controller-manager-metrics-service unchanged
service/kserve-controller-manager-service unchanged
service/kserve-webhook-server-service unchanged
deployment.apps/kserve-controller-manager unchanged
statefulset.apps/kserve-controller-manager unchanged
certificate.cert-manager.io/serving-cert unchanged
issuer.cert-manager.io/selfsigned-issuer unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/inferenceservice.serving.kserve.io configured
validatingwebhookconfiguration.admissionregistration.k8s.io/inferencegraph.serving.kserve.io configured
validatingwebhookconfiguration.admissionregistration.k8s.io/inferenceservice.serving.kserve.io configured
validatingwebhookconfiguration.admissionregistration.k8s.io/trainedmodel.serving.kserve.io configured
```

kubectl describe Inferenceservice

```
Name:         djl-serving-model
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  serving.kserve.io/v1beta1
Kind:         InferenceService
Metadata:
  Creation Timestamp:  2022-09-30T15:48:53Z
  Finalizers:
    inferenceservice.finalizers
  Generation:  1
  Managed Fields:
    API Version:  serving.kserve.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:predictor:
          .:
          f:model:
            .:
            f:modelFormat:
              .:
              f:name:
            f:runtime:
            f:storageUri:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-09-30T15:48:52Z
    API Version:  serving.kserve.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"inferenceservice.finalizers":
    Manager:      manager
    Operation:    Update
    Time:         2022-09-30T15:48:53Z
    API Version:  serving.kserve.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:components:
          .:
          f:predictor:
            .:
            f:latestCreatedRevision:
        f:conditions:
        f:modelStatus:
          .:
          f:states:
            .:
            f:activeModelState:
            f:targetModelState:
          f:transitionStatus:
    Manager:         manager
    Operation:       Update
    Subresource:     status
    Time:            2022-09-30T15:48:54Z
  Resource Version:  6846231
  UID:               165c7b13-d5b8-4036-9d53-1d20f0bd5b0d
Spec:
  Predictor:
    Model:
      Model Format:
        Name:  mxnet
      Name:    
      Resources:
      Runtime:      kserve-djlserving
      Storage Uri:  https://resources.djl.ai/demo/mxnet/resnet18_v1.zip
Status:
  Components:
    Predictor:
      Latest Created Revision:  djl-serving-model-predictor-default-00001
  Conditions:
    Last Transition Time:  2022-09-30T15:48:56Z
    Message:               Revision "djl-serving-model-predictor-default-00001" failed with message: Unable to fetch image "djlserving:replace": failed to resolve image to digest: HEAD https://index.docker.io/v2/library/djlserving/manifests/replace: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details).
    Reason:                RevisionFailed
    Severity:              Info
    Status:                False
    Type:                  PredictorConfigurationReady
    Last Transition Time:  2022-09-30T15:48:56Z
    Message:               Configuration "djl-serving-model-predictor-default" does not have any ready Revision.
    Reason:                RevisionMissing
    Status:                False
    Type:                  PredictorReady
    Last Transition Time:  2022-09-30T15:48:56Z
    Message:               Configuration "djl-serving-model-predictor-default" does not have any ready Revision.
    Reason:                RevisionMissing
    Severity:              Info
    Status:                False
    Type:                  PredictorRouteReady
    Last Transition Time:  2022-09-30T15:48:56Z
    Message:               Configuration "djl-serving-model-predictor-default" does not have any ready Revision.
    Reason:                RevisionMissing
    Status:                False
    Type:                  Ready
  Model Status:
    States:
      Active Model State:  
      Target Model State:  Pending
    Transition Status:     InProgress
Events:                    <none>

```

**Comment by yuzisun** [comment]
@sindhuvahinis you also need to add the default image tag here
https://github.com/kserve/kserve/blob/master/config/runtimes/kustomization.yaml#L12

**Comment by sindhuvahinis** [comment]
@yuzisun yes yes ofcourse, We included in that too. 

kustomization.yaml

```

resources:
  - kserve-tensorflow-serving.yaml
  - kserve-sklearnserver.yaml
  - kserve-mlserver.yaml
  - kserve-xgbserver.yaml
  - kserve-tritonserver.yaml
  - kserve-pmmlserver.yaml
  - kserve-paddleserver.yaml
  - kserve-lgbserver.yaml
  - kserve-torchserve.yaml
  - kserve-djlserving.yaml

images:
  # SMS Only Runtimes
  - name: tensorflow-serving
    newName: tensorflow/serving
    newTag: 2.6.2

  - name: kserve-sklearnserver
    newName: kserve/sklearnserver
    newTag: latest

  - name: mlserver
    newName: docker.io/seldonio/mlserver
    newTag: 1.0.0

  - name: kserve-xgbserver
    newName: kserve/xgbserver
    newTag: latest

  - name: kserve-tritonserver
    newName: nvcr.io/nvidia/tritonserver
    newTag: 21.09-py3

  - name: kserve-pmmlserver
    newName: kserve/pmmlserver
    newTag: latest

  - name: kserve-paddleserver
    newName: kserve/paddleserver
    newTag: latest

  - name: kserve-lgbserver
    newName: kserve/lgbserver
    newTag: latest

  - name: kserve-torchserve
    newName: pytorch/torchserve-kfs
    newTag: 0.6.0

  - name: kserve-djlserving
    newName: docker.io/deepjavalibrary/djl-serving
    newTag: latest
```
