### DISCUSSION TITLE
Custom tritonserver image

### DISCUSSION THREAD

**Discussion by p-constant** [kubeflow/kfserving#2583] [Q&A]
I’m have triton pipeline, which consists [BLS](https://github.com/triton-inference-server/python_backend/blob/main/examples/bls/README.md) with additional packages.
I use it building custom image, installing packages via pip in dockerfile.

Now I want to use pipeline in kserve

But can I load my custom triton image in kserve? Or I can select only tag of official tritonserver image or write custom predictor?

**Comment by yuzisun** [comment]
@TheConstant3 You can either update the image on triton serving runtime [here](https://github.com/kserve/kserve/blob/master/config/runtimes/kserve-tritonserver.yaml#L32) or override the image field on the inference service yaml
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "bert-v2"
spec:
  predictor:
    triton:
      image: custom-triton-image:20.10-py3
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 8Gi
      storageUri: "gs://kfserving-examples/models/triton/bert"
```

**Reply by p-constant** [reply]
Now I apply service:
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: {task_name}
  namespace: {namespace_serving}
  annotations:
    "sidecar.istio.io/inject": "false"
spec:
  predictor:
    triton:
      image: my_image:my_tag
      args:
        - tritonserver
        - --model-store=/mnt/{task_name}
        - --model-control-mode=poll
        - --grpc-port=9000
        - --http-port=8080
        - --allow-grpc=true
        - --allow-http=true
      storageUri: "pvc://{pvc_name}/"
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 8Gi
          nvidia.com/gpu: "1"
```
Folder ```/mnt/{task_name}``` is model repository, with structure ```/mnt/{task_name}/<model_name>/<model_version>...``` 
But service failed with error on screenshot:
![Снимок экрана от 2022-12-05 20-29-27](https://user-images.githubusercontent.com/46416203/205839450-2426ae3c-d1c2-4981-88f6-432e2fb29895.png)

kserve version is 0.7.0
