### DISCUSSION TITLE
How much memory must be assigned to KServe controller manager?

### DISCUSSION THREAD

**Discussion by superfav** [kubeflow/kfserving#2850] [Q&A]
We had to increase the memory limit from 300Mi to 1.2Gi because it was OOM killed with less than 600MI. After almost two weeks it was OOM killed.
Is this expected or are we in the presence of a memory leak?
Default values:
```yaml
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
```
Here you can see the evolution of our settings and the memory usage. `requests.memory` as green dashes and `limits.memory` as red dashes. That last drop was when it was OOM killed for the last time.
![image](https://user-images.githubusercontent.com/732412/234281091-9871e1d9-94e2-47b1-9a3f-e6b376b3bfdf.png)
Thanks.
