### DISCUSSION TITLE
I want to load my models using triton runtime in kserve.

### DISCUSSION THREAD

**Discussion by kwanwoo02** [kubeflow/kfserving#2901] [General]
Hello I am newbie to kserve.
I want to load my models using triton runtime in kserve. But my model directory is not mapped.

Example uses google cloud storage but i want to use my local directory.

my_triton.yaml
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: triton-autoscaling
spec:
  predictor:
    minReplicas: 0
    maxReplicas: 4
    containerConcurrency: 3
    triton:
      # storageUri: gs://kfserving-examples/models/torchscript            # before
      # storageUri: file:///home/ubuntu/workspace/models_directory        # after
      runtimeVersion: 20.10-py3
      resources:
        limits:
          nvidia.com/gpu: 1
```
![image](https://user-images.githubusercontent.com/49938103/232724691-b226d258-03e0-4514-b427-fc991d2a1607.png)

As you can see, it seems that you need to modify the storageurl part.
But I don't know what to do.
let me know if there is a way

What did you expect to happen:

Successful connection with directory in my local and tritonserver
