### DISCUSSION TITLE
How to do authentication of Kserve?

### DISCUSSION THREAD

**Discussion by shauryagoel** [kubeflow/kfserving#3103] [Q&A] [answered]
I wanted to add authentication to my kserve service. So, I found out that Istio provides such features using  `RequestAuthentication`. However, I am not able to make this work for `InferenceService`.  
I have this Kserve service-
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
  namespace: kserve-test
  labels:
    app: sklearn-iris
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: gs://kfserving-examples/models/sklearn/1.0/model
```
Here is my RequestAuthentication-
```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: iris
  namespace: kserve-test
spec:
  selector:
    matchLabels:
      app: sklearn-iris
  jwtRules:
    - issuer: admin@istio.com
      jwks: |-
        <JWKS_TOKEN>
```
After applying both of these files, I pass the token in curl request and nothing happens. Even if I change the token format, it does not give any error. I have applied a similar config to a non kserve deployment and it is working on that service.
