### DISCUSSION TITLE
Path Based Routing

### DISCUSSION THREAD

**Discussion by vinayK34** [kubeflow/kfserving#3796] [Q&A]
Hi, I have a running inferenceservice which expose an API to external. I am looking for a solution where I can control the API path either while creating the inferenceservice using the manifest or creating an custom virtualservice where I can define a different path to the same inferenceservice which is accessible to external, would like know the process.

Below is the current vs that is exposed to a particular path - 

```
spec:
  gateways:
  - knative-serving/knative-local-gateway
  hosts:
  - text-embeddings-inference.user01.svc.cluster.local
  - kserve.ai.wavelet.com
  http:
  - headers:
      request:
        set:
          Host: text-embeddings-inference-predictor.user01.svc.cluster.local
    match:
    - authority:
        regex: ^text-embeddings-inference\.user01(\.svc(\.cluster\.local)?)?(?::\d{1,5})?$
      gateways:
      - knative-serving/knative-local-gateway
    route:
    - destination:
        host: knative-local-gateway.istio-system.svc.cluster.local
        port:
          number: 80
      weight: 100
  - headers:
      request:
        set:
          Host: text-embeddings-inference-predictor.user01.svc.cluster.local
    match:
    - authority:
        regex: ^kserve\.ai\.wavelet\.com(?::\d{1,5})?$
      gateways:
      - knative-serving/knative-local-gateway
      uri:
        prefix: /models/user01/text-embeddings-inference/
    - authority:
        regex: ^kserve\.ai\.wavelet\.com(?::\d{1,5})?$
      gateways:
      - knative-serving/knative-local-gateway
      uri:
        exact: /models/user01/text-embeddings-inference
    rewrite:
      uri: /
    route:
    - destination:
        host: knative-local-gateway.istio-system.svc.cluster.local
        port:
          number: 80
      weight: 100
```

I want to access the model https://kserve.ai.wavelet.com/models/user01/text-embeddings-inference/pipeline/feature-extraction/bge 

Note - Not possible to change the model methos, it has to be through custom path
