### DISCUSSION TITLE
Securing inferenceservices endpoints

### DISCUSSION THREAD

**Discussion by AidenGoodall** [kubeflow/kfserving#3833] [Q&A]
Hey all, 

for the past few days I've been investigating kserve for my production deployments. One thing that isn't clear to me is how to secure my endpoints. I've been trying to setup jwt authentication using the Istio's RequestAuthentication and AuthorizationPolicy.

My deployment has both a transformer and predictor. No matter what I do I can't get e2e inference working though. My requests have made it through to the transformer but they then return an error 403 when trying to go to the predictor. 

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: first-inference-service
  namespace: istio-system
spec:
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: mnist-model
      #istio: ingressgateway # use Istio default gateway implementation
  action: ALLOW
  rules:
    - from:
      - source:
          requestPrincipals: ["*"]
```

```yaml
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-example"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: iss
    jwks: |
      token
```

Has anyone successfully setup jwt auth on a kserve deployment without kubeflow?
