### DISCUSSION TITLE
How to add environment variables to storage-initializer sidecar in `InferenceService`?

### DISCUSSION THREAD

**Discussion by kimminw00** [kubeflow/kfserving#4331] [Q&A]
I understand that for a custom `ClusterStorageContainer`, I can specify environment variables under the `container` section, like this:

```yaml
apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: abc
spec:
  container:
    name: storage-initializer
    image: kubeflow/model-registry-storage-initializer:latest
    env:
    - name: MODEL_REGISTRY_BASE_URL
      value: "$MODEL_REGISTRY_SERVICE.model-registry.svc.cluster.local:$MODEL_REGISTRY_REST_PORT"
    - name: MODEL_REGISTRY_SCHEME
      value: "http"
```

**I'd like to configure different environment variables for each `InferenceService` separately. Is there a way to achieve this without modifying the global `ClusterStorageContainer`**?

Any help or guidance would be greatly appreciated!

Thank you in advance!

**Comment by sivanantha321** [comment]
I think currently it is not possible. Have you tried adding these values to isvc annotations or labels and refer it in the env ?
```
env:
  - name: MODEL_REGISTRY_BASE_URL
    valueFrom:
      fieldRef: 
        fieldPath: metadata.annotations['mycompany.com/model-registry-base-url']
```
