### ISSUE TITLE
Cannot change default CPU and Memory for inferenceservices

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/kfserving#1085]
/kind bug

`kubectl -n kfserving-system edit configmap inferenceservice-config`
```yml
        "sklearn": {
            "image": "gcr.io/kfserving/sklearnserver",
            "defaultImageVersion": "v0.4.0",
            "memoryRequest": "100Mi",
            "memoryLimit": "1Gi",
            "cpuRequest": "100m",
            "cpuLimit": "1"
        },
```

kfserving/sklearn.yaml
```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  default:
    predictor:
      sklearn:
        storageUri: "gs://kfserving-samples/models/sklearn/iris"
#        resources:
#          limits:
#            cpu: 1
#            memory: 500Mi
#          requests:
#            cpu: 100m
#            memory: 250Mi
```
kubectl apply -f kfserving/sklearn.yaml -n kfserving-test

but i still get 

```yml
Spec:
  Default:
    Predictor:
      Sklearn:
        Resources:
          Limits:
            Cpu:     1
            Memory:  2Gi
          Requests:
            Cpu:          1
            Memory:       2Gi
        Runtime Version:  v0.4.0
        Storage Uri:      gs://kfserving-samples/models/sklearn/iris
```

**What did you expect to happen:**

```yml
Spec:
  Default:
    Predictor:
      Sklearn:
        Resources:
          Limits:
            Cpu:     1
            Memory:  1Gi
          Requests:
            Cpu:          100m
            Memory:       100Mi
        Runtime Version:  v0.4.0
        Storage Uri:      gs://kfserving-samples/models/sklearn/iris
```

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
