### ISSUE TITLE
Inference for deployed triton pod fails, is there a way to determine why?

### ISSUE THREAD

**Issue by mokpolar** [kubeflow/kfserving#1091]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I downloaded "mobilenet" and saved it as a pb file, created config.pbtxt and deployed it.

config.pbtxt
```yaml
name: "my_model"
platform: "tensorflow_savedmodel"
max_batch_size: 1
input [{
    name: "input_1"
    data_type: TYPE_FP32
    dims: [ 224, 224, 3 ]
  }
]
output [{
    name: "act_softmax"
    data_type: TYPE_FP32
    dims: [ 1000 ]
  }
]
instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]
```
And after making the image into json file in 224,224,3 form, executed the inference.
And I got 400 Bad Request error. 

I want to know where the problem occurred, but like other inference pods, there is no reason for the failure in the log. 
Is there any way to find out why?

**What did you expect to happen:**
image prediction. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.4.0
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
