### ISSUE TITLE
Kustomize does not replace vars in conversion webhook

### ISSUE THREAD

**Issue by pugangxa** [kubeflow/kfserving#1127]
/kind bug

Deploy kfserving with blow command:
```
Make deploy 
```

And then apply the sklearn sample, report:
➜  sklearn git:(update-controller-gen) ✗ k apply -f sklearn.yaml
Error from server: error when creating "sklearn.yaml": conversion webhook for serving.kubeflow.org/v1alpha2, Kind=InferenceService failed: Post https://$(webhookServiceName).$(kfservingNamespace).svc:443/convert?timeout=30s: service "$(webhookServiceName)" not found 

Seen from logs:
```
E1010 08:14:54.313591       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1beta1.InferenceService: conversion webhook for serving.kubeflow.org/v1alpha2, Kind=InferenceService failed: Post https://$(webhookServiceName).$(kfservingNamespace).svc:443/convert?timeout=30s: service "$(webhookServiceName)" not found
E1010 08:14:55.319109       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1beta1.InferenceService: conversion webhook for serving.kubeflow.org/v1alpha2, Kind=InferenceService failed: Post https://$(webhookServiceName).$(kfservingNamespace).svc:443/convert?timeout=30s: service "$(webhookServiceName)" not found
```

**Comment by pugangxa** [comment]
Run ```kustomize build``` under config/default and the variable is not replaced:

```
        namespace: $(kfservingNamespace)
        name: $(webhookServiceName)
```

**Comment by yuzisun** [comment]
@pugangxa this seems like worked fine for me when I run `kustomize build config/default`
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kfserving-system/serving-cert
    controller-gen.kubebuilder.io/version: v0.3.1-0.20200528125929-5c0c6ae3b64b
  name: inferenceservices.serving.kubeflow.org
spec:
  conversion:
    conversionReviewVersions:
    - v1alpha2
    - v1beta1
    strategy: Webhook
    webhookClientConfig:
      caBundle: Cg==
      service:
        name: kfserving-webhook-server-service
        namespace: kfserving-system
        path: /convert
```
