### ISSUE TITLE
Custom image with pytorch or tensorflow model can't deploy on kfserving, but can deploy successfully as a normal pod.

### ISSUE THREAD

**Issue by rtrobin** [kubeflow/kfserving#1142]
/kind bug

**What steps did you take and what happened:**
I build an image prediction flask app using pytorch. Gunicorn is used to launch multiple pytorch model instances to speedup inference procedure. It works fine on local machine, using docker run command.

When I deploy it on KFServing, the pod is successfully deployed. But python processes are repeatedly rebooted. The service can't run successfully. Also, It can be deployed successfully as a normal pod.

I record a gif to show my case.

![kfserving](https://user-images.githubusercontent.com/8224989/96459059-3e7f1200-1254-11eb-94ee-1ad9dfe27526.gif)

**What did you expect to happen:**

**Anything else you would like to add:**

I pushed all my test code in my repo(https://github.com/rtrobin/codeMixed/tree/master/server). By running `docker build .`, you can build my test docker. Also I pushed my docker into docker hub. You can pull it by `docker pull rtrobin/server:test` as you wish.

The kfserving yaml file is shown below:

``` yaml
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: codemixed
spec:
  default:
    predictor:
      custom:
        container:
          image: rtrobin/server:test
          env:
            - name: WORKER
              value: "2"
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              nvidia.com/gpu: "1"

```

The normal pod delpoy yaml file is shown below:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: Never
  containers:
  - image: rtrobin/server:test
    env:
      - name: WORKER
        value: "2"
    name: torchmodel
    resources:
      limits:
        nvidia.com/gpu: 1
```

The server code is shown below:

``` python
import io
import json

import torch
from torchvision import models
import torchvision.transforms as transforms
from PIL import Image
from flask import Flask, jsonify, request


app = Flask(__name__)
imagenet_class_index = json.load(open('./imagenet_class_index.json'))
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
model = models.densenet121(pretrained=False).to(device)
model.eval()


def transform_image(image_bytes):
    my_transforms = transforms.Compose([transforms.Resize(255),
                                        transforms.CenterCrop(224),
                                        transforms.ToTensor(),
                                        transforms.Normalize(
                                            [0.485, 0.456, 0.406],
                                            [0.229, 0.224, 0.225])])
    image = Image.open(io.BytesIO(image_bytes))
    return my_transforms(image).unsqueeze(0)


def get_prediction(image_bytes):
    tensor = transform_image(image_bytes=image_bytes).to(device)
    with torch.no_grad():
        outputs = model.forward(tensor)
        _, y_hat = outputs.max(1)
        predicted_idx = str(y_hat.item())
    return imagenet_class_index[predicted_idx]


@app.route('/predict', methods=['POST'])
def predict():
    if request.method == 'POST':
        file = request.files['file']
        img_bytes = file.read()
        class_id, class_name = get_prediction(image_bytes=img_bytes)
        return jsonify({'class_id': class_id, 'class_name': class_name})


if __name__ == '__main__':
    app.run()
```

The gunicorn config file is shown below:

``` python
# gunicorn.conf

import os

workers = int(os.environ.get('WORKER', '4'))
bind = '0.0.0.0:' + os.environ.get('PORT', '5000')
daemon = 'false'
worker_connections = 2000
```

The dockerfile is shown below:

``` Dockerfile
FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime

LABEL maintainer="robintang.116@gmail.com"

RUN pip install flask gunicorn gevent \
        --no-cache-dir \
        -i https://mirrors.aliyun.com/pypi/simple

ENV LANG C.UTF-8

COPY ./ /workspace/server
WORKDIR /workspace/server

ENV PORT=5000
ENV WORKER=4

CMD exec gunicorn -c gunicorn.py main:app
```

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.4.0
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
