### ISSUE TITLE
Write a AWS Cognito Guide

### ISSUE THREAD

**Issue by seizadi** [kubeflow/kfserving#1233]
/kind feature

**Describe the solution you'd like**
There is not a clear write up on how to configure AWS Cognito for Kfserving. The current
[kubeflow e2e](https://www.kubeflow.org/docs/aws/aws-e2e/) does not cover kfserving configuration.

There is a good writeup for [GCloud IAP](https://github.com/kubeflow/kfserving/tree/master/docs/samples/gcp-iap#kfserving-gcpiap-example).
 That guide could be used as a model for the AWS Cognito. This would go a long way to avoid having people struggle with the setup for kfserving on AWS.

Recent issues on this:
https://github.com/kubeflow/kfserving/issues/1154
https://github.com/kubeflow/website/issues/2378

**Comment by karlschriek** [comment]
@seizadi do you have some initial pointers here on how to go about it? If I can manage to get it working for us I would be happy to contribute to a documentation afterwards

**Comment by karlschriek** [comment]
If I understood it correctly, all that is needed is to roll out an InferenceService with istio sidecar injection to allow for authorization (https://github.com/kubeflow/kfserving/blob/master/docs/samples/gcp-iap/sklearn-iap-with-authz.yaml) and then start up an additional VirtualService (https://github.com/kubeflow/kfserving/blob/master/docs/samples/gcp-iap/virtual-service.yaml).

We then post requests to the new VirtualService with these cookies:

```
cookies = {'AWSELBAuthSessionCookie-0': 'xxxxxx'
           'AWSELBAuthSessionCookie-1': 'xxxxxx'
          }
```

Seems fairly straightforward. Am I missing anything (aside from the fact that this need KF 1.1+)?

**Comment by seizadi** [comment]
You actually need to disable the istio-sidecar, AuthZ does not work, depending on your requirements, you might not be able to use this in production.

Here is some detail notes I wrote to myself when I was debugging this problem:
https://github.com/seizadi/kubeflow-aws-cognito#debug-model

**Comment by PatrickXYS** [comment]
@seizadi Thanks I'll help on this, will collaborate with @yuzisun to make sure we provide well-written documentation for KFServing on AWS Cognito

**Comment by karlschriek** [comment]
@seizadi I've gone through your notes and am trying to replicate your solution. 

I am rolling out the following:

```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: karl-schriek
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  default:
    predictor:
      sklearn:
        storageUri: "gs://kfserving-samples/models/sklearn/iris"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kfserving-iap
  namespace: karl-schriek
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /kfserving/karl-schriek/sklearn-iris
    route:
    - destination:
        host: cluster-local-gateway.istio-system.svc.cluster.local
      headers:
        request:
          set:
            Host: sklearn-iris-predictor-default.karl-schriek.svc.cluster.local
      weight: 100
    rewrite:
        uri: /v1/models/sklearn-iris
    timeout: 300s
```

And am then sending a REST request with:

```
import json
import requests
import auth

namespace = "karl-schriek"
domain = "dev-kubeflow-120.learn-mlops.com"

# programmatically fetches cookies
cookies = auth.get_auth_cookie(
    host=f"https://www.{domain}",
    from_cache=False,
    return_as_dict=True,
    username="*******"
    password="*******"
)

def infer(inference_url, images_array,  cookies):
    data = json.dumps({"instances": images_array})
    headers = {
        "Content-Type": "application/json",
    }
    response = requests.post(        
        inference_url, 
        data=data,
        headers=headers, 
        cookies=cookies
    )
    response.raise_for_status()
    predictions = response.json()["predictions"]

    results_array = predictions

    return results_array

url = f'https://www.{domain}/kfserving/{namespace}/sklearn-iris:predict'

payload = {
    "instances": [
        [6.8,  2.8,  4.8,  1.4],
        [6.0,  3.4,  4.5,  1.6]
    ]
}


infer(url, payload, cookies)

```

When I do this I get a 403 error. 
```
Exception has occurred: HTTPError
403 Client Error: Forbidden for url: https://www.dev-kubeflow-120.learn-mlops.com/kfserving/karl-schriek/sklearn-iris:predict
```

The cookies are correct. Is there something I am missing or that I've configured incorrecty?

**Comment by seizadi** [comment]
I assume you tested the URL I had posted in the README to validate that your URL & cookies are set correctly?
url = 'https://kubeflow.platform.example.com/pipeline/apis/v1beta1/pipelines?page_token=&page_size=10&sort_by=created_at%20desc&filter='

cookies = {'AWSELBAuthSessionCookie-0': 'xxxxxx'
           'AWSELBAuthSessionCookie-1': 'xxxxxx'
          }

r = requests.get(url=url, cookies=cookies)
result = r.json()

Assuming your requests are making their way through the ALB you can trace where along the packet path you are getting it rejected. You can reference this guide for the packet path:
https://github.com/kubeflow/kfserving/blob/master/docs/KFSERVING_DEBUG_GUIDE.md#debug-kfserving-request-flow, assuming your rewrite rule is setup properly they should be arriving at the Kfserving Pod in the karl-schriek namespace. 

Generally you can use the logs but I did use tcpdump when I was debugging, I don't think you will need it.

**Comment by karlschriek** [comment]
Yes I tested against that URL, the cookies are working. I'll follow your suggestion on tracing the packet path tomorrow. Thanks for the suggestion.

**Comment by karlschriek** [comment]
Did you roll out KFServing with KF or did you make a standalone rollout?

**Comment by karlschriek** [comment]
I wonder if the debug guide https://github.com/kubeflow/kfserving/blob/master/docs/KFSERVING_DEBUG_GUIDE.md#debug-kfserving-request-flow refers to an older version of KF/KFServing

I am on KF 1.2, KFServing 0.4.1

It suggests that running `kubectl get gateway knative-ingress-gateway -n knative-serving -oyaml` should yield a gateway that looks like this:

```
kind: Gateway
metadata:
  labels:
    networking.knative.dev/ingress-provider: istio
    serving.knative.dev/release: v0.12.1
  name: knative-ingress-gateway
  namespace: knative-serving
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

For me this gateway doesn't exist at all (neither when installing KFServing bundled with KF, nor with a standalone KFServing 0.4.1). 

The only gateway I have is `kubeflow/kubeflow-gateway`, which I notice does not allow HTTPS traffic. It only has:

```
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```

Could this be why I am getting `403 Client Error: Forbidden`? @yuzisun , @PatrickXYS do you have any ideas? I am not entirely certain how to proceed with debugging this
