### ISSUE TITLE
invalid memory address or nil pointer dereference in agent

### ISSUE THREAD

**Issue by rmporsch** [kubeflow/kfserving#1317]
/kind bug

**What steps did you take and what happened:**

We deployed the following triton inferenceservice:

```yaml
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "triton-mms"
spec:
  predictor:
    triton:
      args:
      - --log-verbose=1
      resources:
        limits:
          cpu: "1"
          memory: "8Gi"
        requests:
          cpu: "1"
          memory: 8Gi
```

as well as the following TrainedModel

```yaml
apiVersion: "serving.kubeflow.org/v1alpha1"
kind: "TrainedModel"
metadata:
  name: "ourmodelname"
spec:
  inferenceService: triton-mms
  model:
    framework: pytorch
    storageUri: s3:/path-to-container/ourmodelname
    memory: "1Gi"
```

within this s3 container we have stored the following mode:

```
- ourmodelname/
  |_ config.pbtxt
  |_ /1
     |_ model.pt
```

we then observe the following error in the `agent` when loading the mode:
```
{"level":"info","ts":"2021-01-26T08:45:42.264Z","caller":"agent/puller.go:121","msg":"Worker is started for layout"}
{"level":"info","ts":"2021-01-26T08:45:42.264Z","caller":"agent/puller.go:129","msg":"Downloading model from s3:/path-to-container/ourmodelname"}
{"level":"info","ts":"2021-01-26T08:45:42.264Z","caller":"agent/downloader.go:47","msg":"Downloading s3:/path-to-container/ourmodelname to model dir /mnt/models"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x169f489]

goroutine 70 [running]:
github.com/kubeflow/kfserving/pkg/agent/storage.FileExists(0xc0001a4480, 0x7b, 0x1bfab30)
	/go/src/github.com/kubeflow/kfserving/pkg/agent/storage/utils.go:27 +0x99
github.com/kubeflow/kfserving/pkg/agent.(*Downloader).DownloadModel(0xc0003eaa98, 0xc0007c5288, 0x6, 0xc0001a90e0, 0x0, 0x0)
	/go/src/github.com/kubeflow/kfserving/pkg/agent/downloader.go:49 +0x40f
github.com/kubeflow/kfserving/pkg/agent.(*Puller).modelProcessor(0xc0003eaa80, 0xc0007c5288, 0x6, 0xc0001a95c0)
	/go/src/github.com/kubeflow/kfserving/pkg/agent/puller.go:130 +0x273
created by github.com/kubeflow/kfserving/pkg/agent.(*Puller).enqueueModelOp
	/go/src/github.com/kubeflow/kfserving/pkg/agent/puller.go:89 +0x120
```

Interestingly, when we try the same with the example model `cifar10` we do not observe this issue.

**What did you expect to happen:**
Model is loaded successfully 

**Environment:**

- Knative Version: 0.17
- KFServing Version: 0.5.0-rc2
