### ISSUE TITLE
A/B/N rollouts

### ISSUE THREAD

**Issue by mtoslalibu** [kubeflow/kfserving#1324]
/kind feature

**Can I roll-out multiple versions for an inference service simultaneously?**
I see that kfserving (v1beta1) provides canary capability, which is great. Does it also support multiple version rollout at the same time? I want to be able to have 3 or more inference service versions that I would like to experiment with.

**Comment by pugangxa** [comment]
I think it's not supported from Inferenceservice resource since we only exposed canaryTrafficPercent which is to distribute traffic between current canary and last ready revision. But you know actually it's knative service created for an inferenceservice and everytime you update it a new revision for a knative service is created, so you can do it through knative service resource, something like:
```
  traffic:
  - tag: v1
    revisionName: stock-service-example-v1
    percent: 50
  - tag: v2
    revisionName: stock-service-example-v2
    percent: 50
  - tag: latest
    latestRevision: true
    percent: 0
```
