### ISSUE TITLE
Port validation error for readiness/liveness probe on InferenceService custom spec

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#1350]
/kind bug

**What steps did you take and what happened:**
Apply InferenceService v1alpha2 or v1beta1 custom spec with readiness probe and get the following validation error saying "port" is required, however if you specify the port knative validation then fails for not allowing setting the port, so the only walk-around is either skip the validation or set port to 0.

```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: mnist
spec:
  predictor:
    containers:
    - args:
      - --model_name
      - mnist
      command:
      - python
      - -m
      - xxx
      env:
      - name: STORAGE_URI
        value: xxx
      image: xxxx
      name: kfserving-container
      readinessProbe:
        httpGet:
          path: /v1/models/mnist
```
          
```
error: error validating "tf_serving_lambda.yaml": error validating data: ValidationError(InferenceService.spec.predictor.containers[0].readinessProbe.httpGet): missing required field "port" in org.kubeflow.serving.v1beta1.InferenceService.spec.predictor.containers.readinessProbe.httpGet; if you choose to ignore these errors, turn validation off with --validate=false
```

**What did you expect to happen:**
The port is not required for InferenceService build-in framework but this results in a validation error on custom spec, so the port field should be made optional on custom spec as well.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.5.0-rc2
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
