### ISSUE TITLE
connection refused when pulling from cluster-local minio s3 gateway

### ISSUE THREAD

**Issue by adamkgray** [kubeflow/kfserving#1370]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

The agent gets a tcp connection refused error when pulling models via a local minio server in s3 gateway mode

```
Get \"http://storage-minio.storage.svc.cluster.local:9000/<bucket>?prefix=<path>\": dial tcp 172.20.167.92:9000: connect: connection refused
```

**What did you expect to happen:**

It should pull the models

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I can pull the models with the same permissions using the aws s3 client and the mc client

```
kubectl port-forward -n storage svc/storage-minio 9000:9000
---
export AWS_ACCESS_KEY_ID=xxx
export AWS_SECRET_ACCESS_KEY=xxx

aws --endpoint-url http://localhost:9000 s3 sync s3://<bucket>/<path> .
<works>

mc mirror s3/<bucket>/<path>/ .
<works>
```

I can get it with the kubctl port forward and also when I run the commands on a bash container in the k8s cluster.

MinIO as well as the inferenceservice have istio sidecars. But its not an issue since I can pull from the bash container on the cluster which also has a sidecar.

I can also reach minio from the kfserving container:
```
wget storage-minio.storage.svc.cluster.local:9000
--2021-02-11 01:28:54--  http://storage-minio.storage.svc.cluster.local:9000/
Resolving storage-minio.storage.svc.cluster.local (storage-minio.storage.svc.cluster.local)... 172.20.167.92
Connecting to storage-minio.storage.svc.cluster.local (storage-minio.storage.svc.cluster.local)|172.20.167.92|:9000... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-02-11 01:28:55 ERROR 403: Forbidden.
```

I created a secret like this for kfserving

```
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: xxx
  AWS_SECRET_ACCESS_KEY: xxx
kind: Secret
metadata:
  annotations:
    serving.kubeflow.org/s3-endpoint: storage-minio.storage.svc.cluster.local:9000
    serving.kubeflow.org/s3-region: ap-east-1
    serving.kubeflow.org/s3-usehttps: "0"
    serving.kubeflow.org/s3-usevirtualbucket: "false"
```

and attached it to the service account like this

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kfserving
secrets:
- name: storage-credentials
```

Is there a difference between the way the cli `aws` and `mc` get objects versus `s3ObjectDownloader.GetAllObjects()` ?

**Environment:**

- Istio Version: 1.8.3
- Knative Version: 0.20.0
- KFServing Version: 0.5.0 rc2
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", Server Version: version.Info{Major:"1", Minor:"18+"
- OS (e.g. from `/etc/os-release`):
