### ISSUE TITLE
Logger container not being created for explainer spec

### ISSUE THREAD

**Issue by drewbutlerbb4** [kubeflow/kfserving#1404]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Deployed the [AIX explainer](https://github.com/kubeflow/kfserving/tree/master/docs/samples/explanation/aix/mnist#using-aix-to-get-explanations-for-mnist-classifications) and added a logger 
```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "aix-explainer"
  namespace: default
spec:
  predictor:
    containers:
    - name: predictor
      image: aipipeline/rf-predictor:0.4.1
      command: ["python", "-m", "rfserver", "--model_name", "aix-explainer"]
      imagePullPolicy: Always
  explainer:
    logger:
      url: http://message-dumper.default/
      mode: all
    aix:
      type: LimeImages
      config:
        num_samples: "100"
        top_labels: "10"
        min_weight: "0.01"

```

But when I check on the pods I notice the `aix-explainer-explainer-default-dv98t-deployment-68d8755f6dlrr9` has `3/3` with no logger deployed
```
bash-3.2$ kubectl get pods -w
NAME                                                              READY   STATUS    RESTARTS   AGE
aix-explainer-explainer-default-dv98t-deployment-68d8755f6dlrr9   3/3     Running   0          3m13s
aix-explainer-predictor-default-rn6rw-deployment-75bcf8c8fn9ch9   3/3     Running   0          3m12s
message-dumper-j85sv-deployment-6db5fcfd47-mq8jq                  3/3     Running   0          101m
```
And after querying the aix-explainer, no logs can are in the message dumper
```
bash-3.2$ kubectl logs $(kubectl get pod -l serving.knative.dev/service=message-dumper -o jsonpath='{.items[0].metadata.name}') user-container
bash-3.2$ 
```

**What did you expect to happen:**

Similar to what we see when the logger is deployed to the predictor
```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "aix-explainer"
  namespace: default
spec:
  predictor:
    logger:
      url: http://message-dumper.default/
      mode: all
    containers:
    - name: predictor
      image: aipipeline/rf-predictor:0.4.1
      command: ["python", "-m", "rfserver", "--model_name", "aix-explainer"]
      imagePullPolicy: Always
  explainer:
    aix:
      type: LimeImages
      config:
        num_samples: "100"
        top_labels: "10"
        min_weight: "0.01"
```

```
bash-3.2$ kubectl get pods -w
NAME                                                              READY   STATUS    RESTARTS   AGE
aix-explainer-explainer-default-c9wfk-deployment-8cbbcbdb7qc9d2   3/3     Running   0          4m50s
aix-explainer-predictor-default-psd8g-deployment-db8f584fdzhxgj   4/4     Running   0          4m49s
message-dumper-j85sv-deployment-6db5fcfd47-mq8jq                  3/3     Running   0          123m
```
And checking the message dumper after querying the predictor results in receiving the cloudevents created from the requests
```
bash-3.2$ kubectl logs $(kubectl get pod -l serving.knative.dev/service=message-dumper -o jsonpath='{.items[0].metadata.name}') user-container
☁️  cloudevents.Event
Validation: valid
Context Attributes,
  specversion: 1.0
  type: org.kubeflow.serving.inference.request
  source: http://localhost:9081/
  id: 2062b33a-74ed-4b36-b512-9975ff4fe99f
  time: 2021-02-23T23:44:18.143788921Z
  datacontenttype: application/json
Extensions,
  endpoint: 
  inferenceservicenam
...
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17+IKS", GitCommit:"8f82fcbe37a8086624922025f586f48b302f0f28", GitTreeState:"clean", BuildDate:"2021-01-15T02:17:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): `macOS Big Sur 11.2`
