### ISSUE TITLE
Inferenceservice annotations/labels are not passed down to the routing virtualservice

### ISSUE THREAD

**Issue by wengyao04** [kubeflow/kfserving#1406]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

The inferenceservice annotations/labels are not passed down to the kfserving routing virtualservice when updating from v1alpha2 to v1beta1

```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  annotations:
    test: true
  labels:
    app: test
  name: sklearn-iris
  namespace: user1
spec:
  predictor:
    containerConcurrency: 4
    minReplicas: 1
    sklearn:
      name: kfserving-container
      protocolVersion: v1
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
      runtimeVersion: v0.5.0-rc1
      storageUri: s3://platform-test/sklearn/iris
```

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sklearn-iris
  namespace: user1
spec:
  gateways:
  - knative-serving/cluster-local-gateway
  - knative-ingress-gateway.knative-serving
  hosts:
  - sklearn-iris.user1.svc.cluster.local
  - sklearn-iris-user1.test.dev.query.bms.test.com
  http:
  - match:
    - authority:
        regex: ^sklearn-iris\.user1(\.svc(\.cluster\.local)?)?(?::\d{1,5})?$
      gateways:
      - knative-serving/cluster-local-gateway
    - authority:
        regex: ^sklearn-iris-user1\.test\.dev\.query\.bms\.test\.com(?::\d{1,5})?$
      gateways:
      - knative-ingress-gateway.knative-serving
    route:
    - destination:
        host: cluster-local-gateway.istio-system.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Host: sklearn-iris-predictor-default.user1.svc.cluster.local
      weight: 100
```

**What did you expect to happen:**
When updating kfserving from v1alpha2 to v1beta1, the inferenceservice annotations does not passed down the the routing virtualservice (vs). We want it patched to the vs in v1beta1 like it does in v1alpha2

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.7.2
- Knative Version:  v0.17.0  
- KFServing Version:  v0.5.0-rc1  
- Kubeflow version: 
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.16
- OS (e.g. from `/etc/os-release`):
