### ISSUE TITLE
validation webhook error when deploying v1beta1 InferenceService on kfserving v0.50

### ISSUE THREAD

**Issue by TahirHayat** [kubeflow/kfserving#1425]
/kind bug

**What steps did you take and what happened:**
I have deployed kubeflow 1.2 on AKS cluster and then updated kfserving to version 0.5.0 by using kfserving_kubeflow_crds.yaml &  kfserving_kubeflow.yaml from https://github.com/kubeflow/kfserving/releases/tag/v0.5.0

I have two node pools in my AKS cluster, the user node pool has following label and taint defined on it
```
"nodeLabels": {
"pool": "mypool"
  },
  "nodeTaints": [
    "sku=gpu:NoSchedule"
  ]
```

After that I deployed  following sample inferenceservice

```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "flower-sample"
spec:
  predictor:
    tensorflow:
      storageUri: "gs://kfserving-samples/models/tensorflow/flowers"
    nodeSelector:
      pool: mypool
    tolerations:
    - key: sku
      operator: Equal
      value: gpu
      effect: NoSchedule
```

it gives this error when I try to deploy above yaml
` Warning  InternalError  2s (x11 over 7s)  v1beta1Controllers  fails to reconcile predictor: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: must not set the field(s): spec.template.spec.nodeSelector, spec.template.spec.tolerations`

**What did you expect to happen:**
it should deploy the inferenceservice pods on my user node pool as per mentioned node selector and tolerations. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.3.1
- Knative Version: 0.14.3
- KFServing Version: 0.5.0
- Kubeflow version: 1.2
- Kfdef: kfctl_k8s_istio.v1.2.0.yaml
- Kubernetes version: v1.18.14

**Comment by pvaneck** [comment]
In Knative, podspec `nodeSelector` and `tolerations` are disabled, and I'm not sure if there is a way to enable them in Knative 0.14.3. From what I can tell, the ability to enable these as [feature flags](https://knative.dev/docs/serving/feature-flags/) came in Knative 0.17. The next release of KubeFlow will likely include an updated version of Knative that will support these, but in the meantime if you want to use those flags, you'll have to upgrade Knative. If upgrading, you can remove your current installation with:

```
kubectl delete -f https://github.com/knative-sandbox/net-istio/releases/download/v0.14.1/release.yaml
kubectl delete -f https://github.com/knative/serving/releases/download/v0.14.3/serving-core.yaml
```
Then after the old Knative  is finished deleting, apply these manifests which were slightly modified for Kubeflow:

```
kubectl apply -f https://raw.githubusercontent.com/pvaneck/manifests/knative-0.17/common/knative/serving/serving-core.yaml
kubectl apply -f https://raw.githubusercontent.com/pvaneck/manifests/knative-0.17/common/knative/serving/net-istio.yaml
```
You may have to apply serving-core.yaml twice due to a race condition. So just apply it again if you see an error.
After installation, enable the flags:

```
kubectl edit -n knative-serving cm config-features
```
Make sure the spec looks something like:
```yaml
apiVersion: v1
data:
    kubernetes.podspec-nodeselector: "enabled"
    kubernetes.podspec-tolerations: "enabled"
    _example:  |
      ....
```

After all this, your InferenceService should hopefully deploy successfully. We can put some documentation about these flags somewhere for users who want to use them.
