### ISSUE TITLE
Differences between yaml syntax v1alpha2 and v1beta1 (for NodeSelector support)

### ISSUE THREAD

**Issue by danielricks** [kubeflow/kfserving#1500]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I was attempting to add a NodeSelector to my InferenceService yaml file in v1alpha2, but I was getting this error:

`error: error validating "/home/dan/Documents/project/ai-service/tools/dist/gpt-pvc-inference-service-333.yaml": error validating data: [ValidationError(InferenceService.spec.default.predictor): unknown field "nodeSelector" in org.kubeflow.serving.v1alpha2.InferenceService.spec.default.predictor, ValidationError(InferenceService.spec.default.predictor): unknown field "tolerations" in org.kubeflow.serving.v1alpha2.InferenceService.spec.default.predictor, ValidationError(InferenceService.spec.default.transformer): unknown field "nodeSelector" in org.kubeflow.serving.v1alpha2.InferenceService.spec.default.transformer]; if you choose to ignore these errors, turn validation off with --validate=false`

Per [this issue](https://github.com/kubeflow/kfserving/issues/730), NodeSelector support has been added to v1beta1, so I switched versions in order to use the NodeSelector feature. When I did that though, I got the following error:

`
error: error validating "/home/dan/Documents/project/ai-service/tools/dist/gpt-pvc-inference-service-333.yaml": error validating data: [ValidationError(InferenceService.spec): unknown field "default" in org.kubeflow.serving.v1beta1.InferenceService.spec, ValidationError(InferenceService.spec): missing required field "predictor" in org.kubeflow.serving.v1beta1.InferenceService.spec]; if you choose to ignore these errors, turn validation off with --validate=false`

Does the entire yaml file need to be formatted differently in order to switch versions? I've looked for comparable example yaml files that uses v1beta1, but can't seem to find any. Below is the relevant yaml file.

```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: ai-service-dev-333-inference
  labels:
    app: ai-service-dev-333-inference
spec:
  default:

    predictor:
      nodeSelector:
        vng: ai-service-gpu
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule

      parallelism: 1
      minReplicas: 0
      maxReplicas: 5
      tensorflow:
        storageUri: /transformer/models_exported/124M/
        runtimeVersion: "1.15.0-gpu"
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1

    transformer:
      nodeSelector:
          vng: ai-service-cpu
      parallelism: 300
      minReplicas: 0
      maxReplicas: 2
      custom:
        container:
          image: __CONTAINER_IMAGE__
          name: user-container
          resources:
            limits:
              cpu: 1
              memory: 256Mi
            requests:
              cpu: 1
              memory: 256Mi
```

**What did you expect to happen:**
I would have expected the differences between yaml files in v1alpha2 and v1beta1 to be minor, but it seems like quite a few changes need to be made, none of which seem obvious.

**Anything else you would like to add:**
I'm not sure where the NodeSelector portion should go. The current location was a best guess based on my other yaml files.

**Environment:**

- Istio Version:
    client version: 1.9.0
    control plane version: 1.8.2
    data plane version: 1.8.2 (1 proxies)
- Knative Version:
- KFServing Version: 0.5.0
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
    Client: v1.18.5
    Server: v1.18.9
- OS (e.g. from `/etc/os-release`):
    Linux 18.04
