### ISSUE TITLE
Unable to serve on AWS S3

### ISSUE THREAD

**Issue by ajinkya933** [kubeflow/kfserving#1519]
/kind bug

**What steps did you take and what happened:**

I want to serve a pytorch model using kf serving on AWS (i am following this tutorial: https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2/pytorch). Here are my steps:

s3_secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
     serving.kubeflow.org/s3-endpoint: s3://kfserving-samples/models/pytorch/cifar10 # replace with your s3 endpoint
     serving.kubeflow.org/s3-usehttps: "1" # by default 1, for testing with minio you need to set to 0
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
  - name: mysecret
```

```
$ kubectl apply -f s3_secret.yaml

secret/mysecret configured
serviceaccount/sa configured
```

You then set the serviceAccountName on the KFService 

pytorch_serve.yaml

```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "pytorch-s3-cifar10-005"
spec:
  default:
    predictor:
      serviceAccountName: sa
      pytorch:
        storageUri: "s3://kfserving-samples/models/pytorch/cifar10"


```

```
$ kubectl apply -f pytorch_serve.yaml
inferenceservice.serving.kubeflow.org/pytorch-s3-cifar10-005 created
```

I dont get any URL generated in the output

```
$ kubectl get inferenceservice
NAME                     URL                                          READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE

pytorch-s3-cifar10-005                                                False                                      6m15s
```

**What did you expect to happen:**
`$ kubectl get inferenceservice` should have generated URL like: 
`http://pytorch-cifar10-005.default.example.com` 

**Anything else you would like to add:**
Am I missing any steps ? What should I do to make this work ?

**Environment:**

- Kubeflow version: 1.2
- Kubernetes version: (use `kubectl version`): 1.18.9
- OS (e.g. from `/etc/os-release`): ubuntu 18.04

**Comment by yuzisun** [comment]
@ajinkya933 The s3 endpoint should be the aws url which by default is `http://s3.amazonaws.com` not the bucket path

**Comment by ajinkya933** [comment]
@yuzisun 

I have made that change still I get no url generated

on S3 I have model in :

```
s3://kfserving-samples/models/pytorch/cifar10/model.pt
```

where should the model be :

should it be in this ? 
```
s3://kfserving-samples/models/pytorch/cifar10/1/model.pt
```

**Comment by ajinkya933** [comment]
Following up I tried both :
```
s3://kfserving-samples/models/pytorch/cifar10/model.pt
```
and
```
s3://kfserving-samples/models/pytorch/cifar10/1/model.pt
```

but the url is still not generated
if this can help here are pod logs:
```
initContainerStatuses:
    - name: storage-initializer
      state:
        waiting:
          reason: CrashLoopBackOff
          message: >-
            back-off 5m0s restarting failed container=storage-initializer
            pod=pytorch-s3-cifar10-005-predictor-default-glcql-deployment-58xpz_default(ab6971f9-cfee-400f-a9a2-2fcb1c3931a0)
      lastState:
        terminated:
          exitCode: 128
          reason: ContainerCannotRun
          message: >-
            OCI runtime create failed: container_linux.go:370: starting
            container process caused: process_linux.go:459: container init
            caused: setenv: invalid argument: unknown
          startedAt: '2021-04-04T16:14:39Z'
          finishedAt: '2021-04-04T16:14:39Z'
```

**Comment by yuzisun** [comment]
@ajinkya933 Can you help dump the full pod yaml of the predictor? 
`kubectl get pods pytorch-s3-cifar10-005-predictor-default-glcql-deployment-58xpz_default -oyaml`

**Comment by yuzisun** [comment]
Also did you specify with the right s3 credential?

**Comment by ajinkya933** [comment]
@yuzisun  please see attached
[005.zip](https://github.com/kubeflow/kfserving/files/6255167/005.zip)

Yes I have correctly specified s3 credentials according to this template:

```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
     serving.kubeflow.org/s3-endpoint: http://s3.amazonaws.com # replace with your s3 endpoint
     serving.kubeflow.org/s3-usehttps: "1" # by default 1, for testing with minio you need to set to 0
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <my key>
  AWS_SECRET_ACCESS_KEY: <my secret key>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
  - name: mysecret
```

**Comment by yuzisun** [comment]
@ajinkya933 the following envs are wrong, I think you need to recreate the isvc as the change is not taking effect
```
    - name: S3_ENDPOINT
      value: s3://kfserving-samples/models/pytorch/cifar10
    - name: AWS_ENDPOINT_URL
      value: https://s3://kfserving-samples/models/pytorch/cifar10
```
Also make sure your secret is base64 encoded, please check my [updated doc](https://github.com/kubeflow/kfserving/blob/7101beec5d753852ae7ee2d69a6b813bbf814653/docs/samples/storage/s3/README.md).

**Comment by ajinkya933** [comment]
@yuzisun I tried the updated doc. I created a new secret and a service account:
```
secret/kfsecret created
serviceaccount/servicesa created
```
After that I applied `kubectl apply -f pytorch_serve.yaml`

where


pytorch_serve.yaml is :
```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "pytorch-s3-cifar10-servicesa-002"
spec:
  default:
    predictor:
      serviceAccountName: servicesa
      pytorch:
        storageUri: "s3://kfserving-samples/models/pytorch/cifar10/1"

```

 here I get new error now.

With the changed documentaition I am able to download the model from s3 to pod :
```
[I 210405 04:17:36 initializer-entrypoint:13] Initializing, args: src_uri [s3://kfserving-samples/models/pytorch/cifar10/1] dest_path[ [/mnt/models]
[I 210405 04:17:36 storage:35] Copying contents of s3://kfserving-samples/models/pytorch/cifar10/1 to local
[I 210405 04:17:36 storage:60] Successfully copied s3://kfserving-samples/models/pytorch/cifar10/1 to /mnt/models
```

But, however there is another error:
```
[I 210405 04:35:55 storage:35] Copying contents of /mnt/models to local
Traceback (most recent call last):
File "/opt/conda/envs/pytorch-py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/opt/conda/envs/pytorch-py37/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/workspace/pytorchserver/pytorchserver/__main__.py", line 35, in <module>
model.load()
File "/workspace/pytorchserver/pytorchserver/model.py", line 54, in load
model_class = getattr(importlib.import_module(modulename), model_class_name)
AttributeError: module 'cifar10' has no attribute 'PyTorchModel'
```

Any idea whats causing it ?

**Comment by yuzisun** [comment]
@ajinkya933 I think it is missing the model class name, check the example [here](https://github.com/kubeflow/kfserving/blob/master/docs/samples/v1alpha2/pytorch/pytorch.yaml#L10)

**Comment by ajinkya933** [comment]
Its unable to read the model somehow:

```
return cls(name, mode, fileobj, **kwargs)
File "/opt/conda/envs/pytorch-py37/lib/python3.7/tarfile.py", line 1484, in __init__
self.firstmember = self.next()
File "/opt/conda/envs/pytorch-py37/lib/python3.7/tarfile.py", line 2301, in next
raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/conda/envs/pytorch-py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/opt/conda/envs/pytorch-py37/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/workspace/pytorchserver/pytorchserver/__main__.py", line 35, in <module>
model.load()
File "/workspace/pytorchserver/pytorchserver/model.py", line 58, in load
self.model.load_state_dict(torch.load(model_file, map_location=self.device))
File "/opt/conda/envs/pytorch-py37/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
return _load(f, map_location, pickle_module, **pickle_load_args)
File "/opt/conda/envs/pytorch-py37/lib/python3.7/site-packages/torch/serialization.py", line 599, in _load
raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: /mnt/models/model.pt is a zip archive (did you mean to use torch.jit.load()?)
```

I have checked the same on gcp (open source bucket). What can be reason for this jit.load() error ?

**Comment by yuzisun** [comment]
Is this your own torchscript model and the one worked is from the KFServing example bucket? In Kubeflow 1.2 the pytorch model server does not support torchscript model only the eager model, you would need to use TorchServe which was added in KFServing 0.5.

**Comment by ajinkya933** [comment]
I noticed it, your solution generating a url (I downloaded model as it is from google kfserving example bucket) and its creating a url.
Here is a status after I added missing model class name:

```
NAME                               URL                                          READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
s3-test-004                        http://s3-test-004.default.example.com       True    100                                4h13m
```
Now, I try to send curl request but cannot get a predicted response:

```
MODEL_NAME=s3-test-004
curl -v -H "Host: ${SERVICE_HOSTNAME}" -d $INPUT_PATH http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models/$MODEL_NAME:predict | jq

* Expire in 0 ms for 6 (transfer 0x55d98e47cf30)
* Expire in 1 ms for 1 (transfer 0x55d98e47cf30)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Expire in 0 ms for 1 (transfer 0x55d98e47cf30)
* Expire in 2 ms for 1 (transfer 0x55d98e47cf30)
* Expire in 0 ms for 1 (transfer 0x55d98e47cf30)
* Expire in 50 ms for 1 (transfer 0x55d98e47cf30)
*   Trying 3.131.18.35...
* TCP_NODELAY set
* Expire in 149923 ms for 3 (transfer 0x55d98e47cf30)
* Expire in 200 ms for 4 (transfer 0x55d98e47cf30)
* Connected to af956ababa046405b93c16488e8c5eaf-1258816654.us-east-2.elb.amazonaws.com (3.131.18.35) port 80 (#0)
> POST /v1/models/s3-test-004:predict HTTP/1.1
> Host: pytorch-cifar10.default.example.com
> User-Agent: curl/7.64.0
> Accept: */*
> Content-Length: 110681
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
* Expire in 1000 ms for 0 (transfer 0x55d98e47cf30)
< HTTP/1.1 100 Continue
  0  108k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0} [65536 bytes data]
* We are completely uploaded and fine
< HTTP/1.1 404 Not Found
< content-length: 137
< content-type: text/html; charset=UTF-8
< date: Mon, 05 Apr 2021 11:25:50 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 1
< 
{ [137 bytes data]
100  108k  100   137  100  108k     77  62496  0:00:01  0:00:01 --:--:-- 62538
* Connection #0 to host af956ababa046405b93c16488e8c5eaf-1258816654.us-east-2.elb.amazonaws.com left intact
parse error: Invalid numeric literal at line 1, column 17
```
Any pointers how to fix it ?

**Comment by ajinkya933** [comment]
I fixed it corect SERVICE_HOSTNAME=$(kubectl get inferenceservice s3-test-004 -o jsonpath='{.status.url}' | cut -d "/" -f 3)

Thanks for all your patient efforts and apt followups :100:

**Comment by yuzisun** [comment]
Are you passing the wrong host header `pytorch-cifar10.default.example.com`? it should be `s3-test-004.default.example.com` from what you posted.

**Comment by ajinkya933** [comment]
Yup fixed it thanks alot :1st_place_medal:

**Comment by juanvasquezreyes** [comment]
Hello @yuzisun 

I'm facing the same issue AccessDenied: message: Access Denied, I follow the steps described in the [link](https://github.com/kubeflow/kfserving/blob/7101beec5d753852ae7ee2d69a6b813bbf814653/docs/samples/storage/s3/README.md)

this is my secret
```
apiVersion: v1
kind: Secret
metadata:
  name: dev
  annotations:
     serving.kubeflow.org/s3-endpoint: "minio.test.com" # replace with your s3 endpoint e.g minio-service.kubeflow:9000 
     serving.kubeflow.org/s3-usehttps: "0" # by default 1, if testing with minio you can set to 0
     serving.kubeflow.org/s3-region: "us-east-1"     
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AWS_ACCESS_KEY_ID: xxx
  AWS_SECRET_ACCESS_KEY :xxx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev
secrets:
- name: dev
---
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "test"
spec:
  default:
    predictor:
      serviceAccountName: dev
      sklearn:
        storageUri: "s3://bucket/iris"
```

is there something I'm missing

Also tested with https reported in this issue https://github.com/kubeflow/kfserving/issues/1630
