### ISSUE TITLE
Tensorflow serving

### ISSUE THREAD

**Issue by jw-websensa** [kubeflow/kfserving#1534]
/kind feature

I am currently preparing serving for a tensorflow model which is using SCANN library.
As process of model training is automated through KF pipelines, builded model is stored on minio.
In that case I want to use tensorflow kfserving to be able to load model from this storage.
However, using SCANN with TFserving requires custom docker image, prepared by Google - [link](https://hub.docker.com/r/google/tf-serving-scann). 
It would be great to possibly pass custom image to TFserving.

**Comment by yuzisun** [comment]
@jw-websensa this is possible today, on tensorflow spec you can pass the image field provided the assumption that startup arguments are still the same.

```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "scann"
spec:
  predictor:
    tensorflow:
      image: google/tf-serving-scann:latest
      storageUri: "gs://kfserving-samples/models/tensorflow/xxx"
```
