### ISSUE TITLE
New model deployments are missing virtualServices

### ISSUE THREAD

**Issue by ulrikpl** [kubeflow/kfserving#1551]
/kind bug

**What steps did you take and what happened:**

Installed KFServing standalone cluster on GCP, as described below (note commands are copied from a Makefile I use for organising the code)

The problem is that I can only get a single prediction services to work. Any following prediction services have a virtualservice missing. I am unsure what component creates the virtual services and how to configure the cluster to have more than one model run succesfully. Any hints are welcome!

```
# ----------------------------------------
# CLUSTER
# ----------------------------------------
create_cluster:
	gcloud beta container \
	--project $(PROJECT_ID) \
	clusters create $(CLUSTER_NAME) \
	--zone $(ZONE) \
	--no-enable-basic-auth \
	--cluster-version "1.18.16-gke.302" \
	--release-channel "regular" \
	--machine-type "e2-standard-8" \
	--image-type "COS" \
	--disk-type "pd-standard" \
	--disk-size "100" \
	--metadata disable-legacy-endpoints=true \
	--service-account $(ALLAPIS_SERVICE_ACCOUNT) \
	--preemptible \
	--num-nodes "1" \
	--enable-stackdriver-kubernetes \
	--enable-ip-alias \
	--network "projects/$(PROJECT_ID)/global/networks/default" \
	--subnetwork "projects/$(PROJECT_ID)/regions/$(REGION)/subnetworks/default" \
	--default-max-pods-per-node "110" \
	--no-enable-master-authorized-networks \
	--addons HorizontalPodAutoscaling,HttpLoadBalancing,GcePersistentDiskCsiDriver \
	--enable-autoupgrade \
	--enable-autorepair \
	--max-surge-upgrade 1 \
	--max-unavailable-upgrade 0 \
	--enable-shielded-nodes \
	--node-locations $(ZONE)
```

```
# ----------------------------------------
# ISTIO
# ----------------------------------------

ISTIO_VERSION = 1.7.1
ISTIOCTL = ./istio-$(ISTIO_VERSION)/bin/istioctl

get_istioctl:
	curl -L https://istio.io/downloadIstio | ISTIO_VERSION=$(ISTIO_VERSION) TARGET_ARCH=x86_64 sh -

# minimal ---- (autoInject: disabled)

istio_create_manifest:
	sh ./shellscripts/istio-minimal-operator.sh
	mv istio-minimal-operator.yaml manifests_istio/

istio_minimal_install:
	$(ISTIOCTL) install -f manifests_istio/istio-minimal-operator.yaml
```

```
# ----------------------------------------
# KNATIVE
# ----------------------------------------

KNATIVE_VERSION = v0.20.0


install_knative_serving_operator:
	kubectl apply -f https://github.com/knative/operator/releases/download/$(KNATIVE_VERSION)/operator.yaml

install_op_serving:
	kubectl apply -f ./manifests_kn/op_serving.yaml
```

```
# ----------------------------------------
# CERT
# ----------------------------------------

install_cert_manager:
	kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.3.0/cert-manager.yaml
```

```
# ----------------------------------------
# KFSERVING
# ----------------------------------------
TAG=v0.5.1

install_kfserving:
	kubectl apply -f https://github.com/kubeflow/kfserving/releases/download/$(TAG)/kfserving.yaml
```

```
# ----------------------------------------
# Demo
# ----------------------------------------
# init
DEMO_INFERENCE_SERVICE	= ./kfserving/docs/samples/v1beta1/sklearn/v1/sklearn.yaml
DEMO_NAMESPACE			= iris
EXTERNAL_IP				:= $(shell sh -c "kubectl get svc istio-ingressgateway -n istio-system | tail -n 1" | awk '{print $$4}')

# Don't use sidecars with minimal istio install / galley and pilot are missing
# enable_sidecars_demo:
#	kubectl label namespace $(DEMO_NAMESPACE) istio-injection=enabled

# Configurations:
INGRESSGATEWAY      = "ingressGateway" : $$(ingressGateway)
LOCALGATEWAY        = "localGateway" : "knative-local-gateway.knative-serving"
LOCALGATEWAYSERVICE = "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local"

fix1_inferenceservice_configmap:
	kubectl get cm inferenceservice-config -n kfserving-system -o yaml \
	| sed 's/"ingressGateway" :.*/$(INGRESSGATEWAY),/' \
	| sed 's/"localGateway" :.*/$(LOCALGATEWAY),/' \
	| sed 's/"localGatewayService" :.*/$(LOCALGATEWAYSERVICE)/' \
	| kubectl apply -f -

# Add 'XX.XXX.XX.XXX.xip.io' to Knative domain configmap
fix2_configdomain_configmap:
	kubectl patch cm config-domain -n knative-serving --type merge \
  	-p '{"data":{"$(EXTERNAL_IP).xip.io":""}}'
	kubectl get cm config-domain -n knative-serving -o yaml | yq r - "data"

fix3_sklearn_virtualservice:
	kubectl get vs sklearn-iris -n $(DEMO_NAMESPACE) -o yaml \
	| sed 's/cluster-local-gateway/knative-local-gateway/' \
	| kubectl apply -f -

new_namespace:
	kubectl create namespace $(DEMO_NAMESPACE)

deploy_demo:
	kubectl apply -f $(DEMO_INFERENCE_SERVICE) -n $(DEMO_NAMESPACE)

test_url:
	kubectl get inferenceservices sklearn-iris -n $(DEMO_NAMESPACE)

test_endpoint:
	curl -v http://sklearn-iris.$(DEMO_NAMESPACE).$(EXTERNAL_IP).xip.io/v1/models/sklearn-iris:predict -d @./kfserving/docs/samples/v1beta1/sklearn/v1/iris-input.json
```

The demo deployment works as expected using the "test_endpoint" rule (curl command). 

The deployment has installed following 3 virtual services:

>$Kubectl get vs -n iris
>sklearn-iris
>sklearn-iris-predictor-default-mesh
>sklearn-iris-predictor-default-ingress

Problem: When ever I deploy another model under another namespace the 'sklearn-iris' virtualService is missing and I only get the mesh and ingress virtual services. Thus I also get no URL like this:

```
kubectl get inferenceservices sklearn-iris -n iris
NAME           URL   READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION   AGE
sklearn-iris                                                                               20m
```

- It is the same issue when using a torch demo deployment.
- The problem persist if I delete and redeploy the inference service deployments and namespace. 

**What did you expect to happen:**
I expected that I could deploy more than one model to the KFServing cluster

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: v1.7.1
- Knative Version: V0.20.0
- KFServing Version: v0.5.1
- Kubeflow version: stand-alone cluster
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: Using GKE
- Kubernetes version: (use `kubectl version`): Client Version: v1.18.15 / Server Version: v1.18.16-gke.502
- OS (e.g. from `/etc/os-release`): MacOS v10.15.7

**Comment by yuzisun** [comment]
@ulrikpl can you dump more details with `kubectl get inferenceservices sklearn-iris -n iris -oyaml` ?

**Comment by ulrikpl** [comment]
```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kubeflow.org/v1beta1","kind":"InferenceService","metadata":{"annotations":{},"name":"sklearn-iris","namespace":"iris"},"spec":{"predictor":{"sklearn":{"storageUri":"gs://kfserving-samples/models/sklearn/iris"}}}}
  creationTimestamp: "2021-04-24T08:11:35Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 1
  managedFields:
  - apiVersion: serving.kubeflow.org/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:predictor:
          .: {}
          f:sklearn:
            .: {}
            f:storageUri: {}
    manager: kubectl
    operation: Update
    time: "2021-04-24T08:11:33Z"
  - apiVersion: serving.kubeflow.org/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers: {}
      f:status: {}
    manager: manager
    operation: Update
    time: "2021-04-24T08:11:35Z"
  name: sklearn-iris
  namespace: iris
  resourceVersion: "23927"
  selfLink: /apis/serving.kubeflow.org/v1beta1/namespaces/iris/inferenceservices/sklearn-iris
  uid: 59bf598e-0dd5-432b-b206-82d9e9b8a0cc
spec:
  predictor:
    sklearn:
      name: kfserving-container
      protocolVersion: v1
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
      runtimeVersion: v0.5.1
      storageUri: gs://kfserving-samples/models/sklearn/iris
```

It seems that editing the configmaps has something to do with this behavior. 
patching configmaps "inferenceservice-config -n kfserving-system" and "config-domain -n knative-serving" as per makefile rules fix1_inferenceservice_configmap and fix2_configdomain_configmap resp. before deploying the inference service reproduces the issue with the missing sklearn virtual service. 

```
$kubectl get cm config-domain -n knative-serving -o yaml | yq r - "data"
{
    "ingressGateway" : $(ingressGateway),
    "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
    "localGateway" : "knative-local-gateway.knative-serving",
    "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local"
}
```

```
$kubectl patch cm config-domain -n knative-serving --type merge \
  	-p '{"data":{"$(EXTERNAL_IP).xip.io":""}}'

$kubectl get cm config-domain -n knative-serving -o yaml | yq r - data
_example: |
  ################################
  #                              #
  #    EXAMPLE CONFIGURATION     #
  #                              #
  ################################

  # This block is not actually functional configuration,
  # but serves to illustrate the available configuration
  # options and document them in a way that is accessible
  # to users that `kubectl edit` this config map.
  #
  # These sample configuration options may be copied out of
  # this example block and unindented to be in the data block
  # to actually change the configuration.

  # Default value for domain.
  # Although it will match all routes, it is the least-specific rule so it
  # will only be used if no other domain matches.
  example.com: |

  # These are example settings of domain.
  # example.org will be used for routes having app=nonprofit.
  example.org: |
    selector:
      app: nonprofit

  # Routes having the cluster domain suffix (by default 'svc.cluster.local')
  # will not be exposed through Ingress. You can define your own label
  # selector to assign that domain suffix to your Route here, or you can set
  # the label
  #    "serving.knative.dev/visibility=cluster-local"
  # to achieve the same effect.  This shows how to make routes having
  # the label app=secret only exposed to the local cluster.
  svc.cluster.local: |
    selector:
      app: secret
34.89.60.117.xip.io: ""
```
