### ISSUE TITLE
No url to call Pod when minReplicas set to 0 because Pod is terminated before it is ready

### ISSUE THREAD

**Issue by shydefoo** [kubeflow/kfserving#1641]
/kind bug

**What steps did you take and what happened:**
* Set minreplicas to 0
* Set large enough resource requests
```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "model-server-01"
  annotations:
    traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
spec:
  predictor:
    minReplicas: 0
    maxReplicas: 1
    tensorflow:
      storageUri: "gs://kfserving-samples/models/tensorflow/flowers"
      resources:
        requests:
          cpu: 8
          memory: 25G
        limits:
          cpu: 8
          memory: 25G
``` 
* We have node autoscaling in place to spin up new nodes when there are insufficient resources
* After some time the pod is scheduled and storage initializer init container starts to download the artifact
* However, since `minReplicas` is set to 0, the pod gets terminated in the midst of downloading (before kfserving-container is ready)
*this leads to the isvc `Ready` status to be `False` and is NO url provided to call to spin up a new Pod in this case
* 
```
status:
  components:
    predictor:
      latestCreatedRevision: model-server-01-predictor-default-tjn8k
  conditions:
  - lastTransitionTime: "2021-06-02T03:59:45Z"
    message: Configuration "model-server-01-predictor-default" does not have any ready
      Revision.
    reason: RevisionMissing
    severity: Info
    status: "False"
    type: PredictorConfigurationReady
  - lastTransitionTime: "2021-06-02T03:59:45Z"
    message: Configuration "model-server-01-predictor-default" does not have any ready
      Revision.
    reason: RevisionMissing
    status: "False"
    type: PredictorReady
  - lastTransitionTime: "2021-06-02T04:01:46Z"
    message: 'Revision "model-server-01-predictor-default-tjn8k" failed with message:
      .'
    reason: RevisionFailed
    severity: Info
    status: "False"
    type: PredictorRouteReady
  - lastTransitionTime: "2021-06-02T03:59:45Z"
    message: Configuration "model-server-01-predictor-default" does not have any ready
      Revision.
    reason: RevisionMissing
    status: "False"
    type: Ready

```

**What did you expect to happen:**
* A url provided after scale to 0 kicks in to trigger the scale up of pods / some way to prevent this from occuring

**Anything else you would like to add:**

**Environment:**

- Istio Version: 1.6.2
- Knative Version: v0.18.0
- KFServing Version: v0.5.1
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): v1.18.18
- OS (e.g. from `/etc/os-release`):
