### ISSUE TITLE
Serving request keep restarting if timeout is reached

### ISSUE THREAD

**Issue by Luke035** [kubeflow/kfserving#1663]
/kind bug

**What steps did you take and what happened:**
A created a simple custom service that waits 60 seconds before returning a simple "OK"
```
    def predict(self, request: Dict) -> Dict:
        print("Received request")
        time.sleep(60)
        return {"predictions": "OK"}
```
Then I created an Inference service that uses this model with a timeout of 30 seconds
```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: test-timeout-model
  namespace: REDACTED
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 3
    containerConcurrency: 2
    serviceAccountName: REDACTED
    timeout: 30
    containers:
      - image: REDACTED 
        name: test-timeout-model
        env:
          - name: KF_SERVER_WORKERS
            value: "1"
        resources:
          requests:
            memory: "1Gi"
            cpu: 1
          limits:
            memory: "1Gi"
            cpu: 1
```

After 60 seconds I get a 504 timeout error but the pod is executing the same request for several times (blocking resources within the container)
```
Received request
[I 210615 09:32:11 web:2243] 200 POST /v1/models/TestTimeoutModel:predict (127.0.0.1) 60060.80ms
Received request
[I 210615 09:33:11 web:2243] 200 POST /v1/models/TestTimeoutModel:predict (127.0.0.1) 60063.01ms
Received request
[I 210615 09:34:11 web:2243] 200 POST /v1/models/TestTimeoutModel:predict (127.0.0.1) 120066.94ms
Received request
[I 210615 09:35:11 web:2243] 200 POST /v1/models/TestTimeoutModel:predict (127.0.0.1) 60018.42ms
```

**What did you expect to happen:**
Request is executed, timeout is returned and no other request are executed within the pod

**Anything else you would like to add:**
KFserving version 0.5.0 running on EKS cluster version 1.18

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.5.0
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.18
- OS (e.g. from `/etc/os-release`): Linux AWS
