### ISSUE TITLE
Can not get logs from raw deployment by web-app

### ISSUE THREAD

**Issue by LuBingtan** [kubeflow/kfserving#1775]
/kind bug

**What steps did you take and what happened:**
1. create an inference service
```yaml
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "flower-sample"
  annotations: 
    serving.kubeflow.org/raw: "true"
spec:
  predictor:
    tensorflow:
      storageUri: "gs://kfserving-samples/models/tensorflow/flowers"
```
2. Then I tried to get logs of the isvc by web-app, but got an error

**What did you expect to happen:**
Get logs from raw deployment by web-app

**Anything else you would like to add:**

**Environment:**

- Istio Version: None
- Knative Version: None
- KFServing Version: master
- Kubeflow version: None
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: v1.18.1
- Kubernetes version: (use `kubectl version`): v1.20.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04
