### ISSUE TITLE
How to setup sklearn prediction v2 (MLServer) with gRPC and MultiModelServer ?

### ISSUE THREAD

**Issue by molejnik-mergebit** [kubeflow/kfserving#1785]
/kind question

> "sklearn": {
>           "v1": {
>             "image": "gcr.io/kfserving/sklearnserver",
>             "defaultImageVersion": "latest",
>             "supportedFrameworks": [
>               "sklearn"
>             ],
>             "multiModelServer": true
>           },
>           "v2": {
>             "image": "docker.io/seldonio/mlserver",
>             "defaultImageVersion": "0.2.1",
>             "supportedFrameworks": [
>               "sklearn"
>             ],
>             "multiModelServer": false
>           }
>         },

Is it possible to configure sklearn predictor (v2) for multi model serving? I already have v1 version working fine in MML setup (i.e. with InferenceService and TrainedModels) - it does what is suppose to do and I'm happy with it. But I wanted to switch from HTTP/REST interface to the gRPC and for that I need to replace Sklearnserver (v1) with SeldonIO/MLServer (v2). But this does not seem to suport MML prediction right now... Is it any plan to support it in the near future or am I configuring sth wrong here?

**Comment by yuzisun** [comment]
@molejnik-mergebit it should work actually, we have not turned on the flag by default but you could try out.

**Comment by molejnik-mergebit** [comment]
Thank you for the reply. I just found I was using kfserving 0.5.0-rc2. I will update to 0.6.1 and will try again.

**Comment by molejnik-mergebit** [comment]
It works for me now on kfserving 0.6.1. Worth mentioning (because I didn't see it anywhere in the docs) that the correct setup for MMS with mlserver is as follows:

inferenceservice.yaml  - standard, without storageUri for MMS

trainedmodel.yaml

```
apiVersion: "serving.kubeflow.org/v1alpha1"
kind: "TrainedModel"
metadata:
  name: "actual-model-name"
spec:
  inferenceService: "proper-inferenceservice-name"
  model:
    storageUri: "gs://bucket-name/some/path"
    framework: "sklearn"
    memory: "128Mi"
```

Then in your GCP bucket, under `bucket-name/some/path` you must place 2 files:
model.joblib - actual model file
model-settings.json - settings file under the default name, which includes:

```
{
    "name": "actual-model-name",
    "implementation": "mlserver_sklearn.SKLearnModel",
    "parameters": {
        "uri": "/mnt/models/actual-model-name/model.joblib"
    }
}
```

Make sure your model name (`actual-model-name` in my example) is the same in trainedmodel.yaml and model-settings.json. Make sure you constructed model.parameters.uri in model-settings.json file as in example above, so it contains model name - this is the place where agent container in MMS configuration will download your model.joblib.

**Comment by molejnik-mergebit** [comment]
Ok, so apparently the inferenceservice.yaml is not "standard". One has to enable proper GRPC port for the whle thing to be available from outside the cluster:

```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "inference-svc-grpc"
spec:
  predictor:
    minReplicas: 1
    sklearn:
      protocolVersion: v2
      name: "predictor-grpc"
      ports:
        - name: h2c
          containerPort: 9000
          protocol: TCP
      resources:
        limits:
          cpu: 1500m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 2Gi
```
