### ISSUE TITLE
Custom Predictor unable to leverage gpu processing. 

### ISSUE THREAD

**Issue by plainenough** [kubeflow/kfserving#1802]
Linked for clarity.

https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/custom/custom_model
Following these instructions I am unable to get a kfserving container to leverage gpu when running a prediction. This container works in kfserving and will return a prediction, obviously cpu processing is way slower than gpu. 

Here is some snippets for context.  Example deployment YAML. 
```
apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: mypredictor
  labels:
    app: mypredictor
spec:
  predictor:
    nodeSelector:
      vng: gpu-node
    containers:
      - name: mypredictor
        image: image-name
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: 8Gi
          requests:
            nvidia.com/gpu: 1
            memory: 4Gi
```

This is probably a simple configuration issue on my part: 

Procfile: 
`web: python -m custom_model`

Custom_model.py - Note my generate.py leverages torchserve-gpu. This code works as expected, and when I build a container with a custom flask front end I am able to leverage gpu with no issues. 
```
import kfserving
from typing import Dict
import generator


class MyModel(kfserving.KFModel):
    """Wrap Generator with kfserving."""
    def __init__(self, name: str):
        super().__init__(name)
        self.name = name
        self.load()

    def load(self):
        """Pass since model files are baked into container."""
        pass

    def predict(self, request: Dict) -> Dict:
        """Execute generator class and return the result."""
        payload = []
        for instance in request['instances']:
            g = generator.Generator()
            if instance['context']:
                g.input_text = instance['context']
            if instance['length']:
                g.generation_length = instance['length']
            if instance['temperature']:
                g.temperature = instance['temperature']
            _payload = g.generate()
            payload.extend(_payload)
            print("Returining:\n {0}\n".format(payload))
        return dict(predictions=payload)


if __name__ == "__main__":
    print("Starting model")
    model_name = "mymodel"
    model = MyModel(model_name)
    kfserving.KFServer().start([model])
```
**What I am using to build the kfserving container**
`pack build --builder=heroku/buildpacks:20 myuser:myimage`

**What I am seeing.**
When I run this container locally on docker: 
`docker run --gpus all --rm  -p 8080:8080 myuser:myimage`
 
When I send a request using curl to my localhost container htop shows cpu usage, nvidia-smi show 0% usage.

I am able to observe the gpu usage using other containers, I'm just not sure what is required to get this running correctly. 

What do I need to do to build a container that will leverage gpu processing?
