### ISSUE TITLE
V1Alpha2: Add Istio virtual service to map services under single domain

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#326]
/kind feature

**Describe the solution you'd like**
KFService v1alpha2 starts to create multiple knative services to support predictor, explainer and transformer, in order to map these services to different paths under a single domain we need to use istio virtual service. According to Ellis's data plane specification(https://docs.google.com/document/d/1scfWSB4d8GeC03riu4AVhdG5sD1I0ZRO4mUhfN6aXAg/edit), we will have two verbs "predict" and "explain" for data plane v1 API.

 

**Anything else you would like to add:**
The virtual service may look like following, `KFService` control plane reconciles the virtual service for `predict` verb to rewrite to `flowers-sample-predictor.ns.example.com` or `flowers-sample-transformer.ns.example.com` route based on `KFService` endpoint spec.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flowers-sample-route
  namespace: default
spec:
  # This is the gateway shared in knative service mesh.
  gateways:
  - knative-ingress-gateway.knative-serving.svc.cluster.local
  # Set host to the domain name that you own.
  hosts:
  - flowers-sample.ns.example.com
  http:
  - match:
    - uri:
      prefix: "/v1/models/flowers-sample:predict"
    rewrite:
      # Rewrite the original host header to the host header of predictor service
      # or transformer service.
      authority: flowers-sample-predictor.ns.example.com
      # or authority: flowers-sample-transformer.ns.example.com
    route:
      # knative-ingressgateway is the k8s service created by Knative as the
      # shared gateway of all traffic incoming to the cluster.
      # Basically here we redirect the request to the cluster entry again with
      # updated header "flowers-sample-predictor.ns.example.com" so the request will
      # eventually be directed to Predictor service.
      - destination:
          host: istio-ingressgateway.istio-system.svc.cluster.local
        weight: 100
  - match:
    - uri:
      prefix: "/v1/models/flowers-sample:explain"
    rewrite:
      # Rewrite the original host header to the host header of explain service
      # in order to redirect requests to Explain service.
      authority: flowers-sample-explainer.default.example.com
    route:
      # Basically here we redirect the request to the cluster entry again with
      # updated header "flowers-sample-explainer.ns.example.com" so the request will
      # eventually be directed to Explain service.
      - destination:
          host: istio-ingressgateway.istio-system.svc.cluster.local
        weight: 100
```

**Comment by yuzisun** [comment]
@rakelkar

**Comment by rakelkar** [comment]
works (aka creates stuff - need to verify virtual service)!

sample status:
```
$ k get kfservice
NAME      URL                                                              READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
httpbin   http://httpbin.default.104.210.45.165.xip.io/v1/models/httpbin   True    50                50               36s
```

detailed status:
```
  status:
    canary:
      predictor:
        host: httpbin-predictor-canary.default.104.210.45.165.xip.io
        name: httpbin-predictor-canary-6vphh
    canaryTraffic: 50
    conditions:
    - lastTransitionTime: "2019-10-04T06:50:07Z"
      severity: Info
      status: "True"
      type: CanaryPredictorReady
    - lastTransitionTime: "2019-10-04T06:50:07Z"
      status: "True"
      type: DefaultPredictorReady
    - lastTransitionTime: "2019-10-04T06:50:07Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2019-10-04T06:50:07Z"
      status: "True"
      type: RoutesReady
    default:
      predictor:
        host: httpbin-predictor-default.default.104.210.45.165.xip.io
        name: httpbin-predictor-default-nt8dp
    traffic: 50
    url: http://httpbin.default.104.210.45.165.xip.io/v1/models/httpbin
```
