### ISSUE TITLE
Ready state not updated correctly

### ISSUE THREAD

**Issue by rakelkar** [kubeflow/kfserving#347]
/kind bug

**What steps did you take and what happened:**
First apply:
```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "KFService"
metadata:
  name: "style-sample"
spec:
  annotations:
  default:
    predictor:
      minReplicas: 1
      onnx:
        storageUri: "https://kfserving.blob.core.windows.net/examples/onnx/style/model.onnx"
  canaryTrafficPercent: 10
  canary:
    predictor:
      minReplicas: 1
      onnx:
        storageUri: "https://kfserving.blob.core.windows.net/examples/onnx/style/model.onnx"
```

Wait for status to move to ready...

Then apply:
```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "KFService"
metadata:
  name: "style-sample"
spec:
  annotations:
  default:
    predictor:
      minReplicas: 1
      onnx:
        storageUri: "https://kfserving.blob.core.windows.net/examples/onnx/style/model.onnx"
  canaryTrafficPercent: 50
  canary:
    predictor:
      minReplicas: 1
      tensorflow:
        storageUri: "gs://mybucket/mymodel-2"
```

status shows ready:
```
$ k get kfservice
NAME           READY   URL                                                         DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
style-sample   True    http://style-sample-predict.default.104.210.45.165.xip.io   50                50               9h
```

But in reality new canary pod is crashing... 
```
$ k get po
NAME                                                              READY   STATUS                  RESTARTS   AGE
style-sample-predictor-canary-5j9x6-deployment-5db596675d-hqnht   0/2     Init:CrashLoopBackOff   4          2m17s
style-sample-predictor-canary-mcvjf-deployment-664cf8544-xc5nw    2/2     Running                 0          5m20s
style-sample-predictor-default-nb4df-deployment-fbcff5975-v62lg   2/2     Running                 0          30h
```

**What did you expect to happen:**
Expected to see an error since canary failed... I guess this is because knative is keeping the old canary revision around :) but that is not what I expected!

```
$ k get revision
NAME                                   CONFIG NAME                      K8S SERVICE NAME                       GENERATION   READY   REASON
style-sample-predictor-canary-5j9x6    style-sample-predictor-canary    style-sample-predictor-canary-5j9x6    2            False   PodInitializing
style-sample-predictor-canary-mcvjf    style-sample-predictor-canary    style-sample-predictor-canary-mcvjf    1            True    
style-sample-predictor-default-nb4df   style-sample-predictor-default   style-sample-predictor-default-nb4df   1            True    
```
