### ISSUE TITLE
Controller crashes on empty model, explainer, transformer spec

### ISSUE THREAD

**Issue by ellis-bigelow** [kubeflow/kfserving#396]
/kind bug
Looks like the defaulter runs first, which can cause crashes if the validator hasn't rejected yet.
```
apiVersion: serving.kubeflow.org/v1alpha2
kind: KFService
metadata:
  name: feast-sample
spec:
  default:
    predictor:
      tensorflow:
        storageUri: gs://kfserving-samples/models/tensorflow/flowers
    transformer: {}
```
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
