### ISSUE TITLE
TRTIS image requires token so default server not launchable

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow/kfserving#654]
/kind bug

NVIDIA TRTIS images require a token so the out of the box tensorrt predictor is not usable unless the user has downloaded or mirrored the image on their cluster. The docs should be updated to state this limitation.

There is also https://github.com/kubeflow/kfserving/issues/163 with https://github.com/kubeflow/kfserving/issues/163#issuecomment-570950399 which discussed the fact we need to wait for the v2 kfserving data plane to fully support trtis.

**Comment by yuzisun** [comment]
the fix is to add `ncvr.io` to the `config-deployment` configmap in knative-serving namespace per [knative tag resolution](https://knative.dev/docs/serving/tag-resolution) 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-deployment
  namespace: knative-serving

data:
  # List of repositories for which tag to digest resolving should be skipped
  registriesSkippingTagResolving: ncvr.io
```
