### ISSUE TITLE
PVC Support is broken: code symlinks instead of copying 

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kfserving#674]
/kind bug

**What steps did you take and what happened:**

* Run tensorflow example, but with a PVC: https://github.com/kubeflow/kfserving/tree/master/docs/samples/tensorflow
```yaml
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "flowers-sample-pvc"
spec:
  default:
    predictor:
      tensorflow:
        storageUri: "pvc://kfserving-pvc/flowers"

```
* KFServing's initContainer symlinks files from a PVC into a shared emptyDir volume.
* These symlinks are obviously invalid inside the main container.

**What did you expect to happen:**

* KFServing should copy the files to the shared emptyDir volume, not symlink them.

**Anything else you would like to add:**

I suspect the bug is in this code:
https://github.com/kubeflow/kfserving/blob/f98acc5a90e530f6599753250572c7f6b1f385e2/python/kfserving/kfserving/storage.py#L188

**Environment:**

- Istio Version: 1.1.6
- Knative Version: 0.8.0
- KFServing Version: 0.2.2
- Kubeflow version: 0.7

/cc @cven @cliveseldon @ellis-bigelow @animeshsingh
