### ISSUE TITLE
Support for TensorFlow 2.0 runtimes

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/kfserving#687]
Currently KFServing only support the following TensorFlow runtimes: 1.11.0, 1.11.0-gpu, 1.12.0, 1.12.0-gpu, 1.13.0, 1.13.0-gpu, 1.14.0, 1.14.0-gpu.

TensorFlow 2.0 has been out for quite some time now. All of our productive models are trained with it. Are there plans to start supporting 2.0 in KFServing?

**Comment by cliveseldon** [comment]
Yes we should update to allow TFServing 2 images in configmap.
We should also check how NVIDIA TRTIS which supports Tensorflow allows Tensorflow 2 models.

**Comment by divyaprabha123** [comment]
Can I raise a PR for this?

**Comment by yuzisun** [comment]
@divyaprabha123  Yes! Looking forward to your PR.

**Comment by yuzisun** [comment]
KFServing has stopped maintaining the allowed version for each framework as of 0.4 release, user should be able to overwrite the docker image version with `runtimeVersion` field under framework spec, here is an example.

```yaml
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "flowers-sample-tf2"
spec:
  default:
    predictor:
      tensorflow:
        runtimeVersion: 2.0.0      
        storageUri: "gs://kfserving-samples/models/tensorflow/flowers"
```
