### ISSUE TITLE
Can not curl top level KFServing virtual service with https

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#722]
/kind bug

**What steps did you take and what happened:**
We have setup istio ingress gateway with https, however curl does not work when calling KFServing top level virtual service, note that we changed knative domain template to `{{name}}-{{namespace}}` to work with wildcard cert.
```
curl -vvv -k https://sklearn-iris-test.example.com/v1/models/sklearn-iris:predict -d @input.json

< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Tue, 10 Mar 2020 14:58:13 GMT
< server: istio-envoy
< 
* Connection #0 to host sklearn-iris-test.example.com left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

**What did you expect to happen:**
https call should work

**Anything else you would like to add:**
The issue seems to be that the top level virtual service is directing to local gateway on port 443 which isn't there.
```
  route:
    - destination:
        host: cluster-local-gateway.istio-system.svc.cluster.local
      headers:
        request:
          set:
            Host: sklearn-iris-predictor-default.test.svc.cluster.local
```

 However it works if we directly call to the default predictor virtual service
```
curl -vvv -k https://sklearn-iris-default-predictor-test.example.com/v1/models/sklearn-iris:predict -d @input.json
```

**Environment:**

- Istio Version: 1.1.7
- Knative Version: 0.12.1
- KFServing Version: master
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
