### ISSUE TITLE
How to set  autoscale target by sdk

### ISSUE THREAD

**Issue by Iamlovingit** [kubeflow/kfserving#756]
/kind bug
This is the example of custom autoscale for yaml
```yaml
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "flowers-sample"
  annotations:
    autoscaling.knative.dev/target: "10"
spec:
  default:
    predictor:
      tensorflow:
        storageUri: "gs://kfserving-samples/models/tensorflow/flowers"
```
I cannot find the method to config this target by sdk.  How to config it by sdk?
