### ISSUE TITLE
Pods of the InferenceService are not created when using GCS  ServiceAccount credentials

### ISSUE THREAD

**Issue by kangwoo** [kubeflow/kfserving#766]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I created an `InferenceService` that uses GCS, but a pod is not created.

```
gcloud iam service-accounts keys create gcp-sa-credentials.json \
  --iam-account [SA-NAME]@[PROJECT-ID].iam.gserviceaccount.com
  
  
kubectl -n [NAMESPACE] create secret generic user-gcp-sa \
  --from-file=gcloud-application-credentials.json=gcp-sa-credentials.json
```
ServiceAccount
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcs-sa
secrets:
- name: user-gcp-sa
```

inference-service.yaml
```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "mnist-gcs"
spec:
  default:
    predictor:
      serviceAccountName: gcs-sa
      tensorflow:
        storageUri: "gs://my-bucket/mnist/model"
```
Revision -> Deployment -> Replicaset (O)-> Pod(X)

Replicaset error
```
status:
  conditions:
  - lastTransitionTime: "2020-04-05T06:14:27Z"
    message: 'Pod "mnist-gcs-predictor-default-dgsss-deployment-7dd6d67df4-mtfkr"
      is invalid: spec.volumes[4].name: Duplicate value: "user-gcp-sa"'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 1
  replicas: 0
```

The `user-gcp-sa` volume is defined in the deployment's pod spec, but it seems to be a problem that occurs when the `user-gcp-sa` volume is duplicated by the pod mutator when the pod is created.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 
- Knative Version: 
- KFServing Version: 0.2.2
- Kubeflow version: 1.0.1
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.15.1
- OS (e.g. from `/etc/os-release`):
