### ISSUE TITLE
Make KFServing accessible from GCP IAP Ingress

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#824]
/kind feature

**Describe the solution you'd like**
This is a follow up for https://github.com/kubeflow/kfserving/issues/760

in GCP/IAP setup, KFServing inference service is protected behind IAP and in order to access from outside, we need additional virtual service rule to work with path based routing because currently KFServing only supports host based routing. So we need to add additional rule in KFServing top level virtual service to rewrite url path and convert to host based routing. 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kfserving-kubeflow-yuzi-dan-kfserving-test
  namespace: kubeflow-yuzi-dan
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /kfserving/kubeflow-yuzi-dan/sklearn-iris
    rewrite:
        uri: /v1/models/sklearn-iris:predict
    route:
    - destination:
        host: cluster-local-gateway.istio-system.svc.cluster.local
      headers:
        request:
          set:
            Host: sklearn-iris-predictor-default.kubeflow-yuzi-dan.svc.cluster.local
      weight: 100
    timeout: 300s
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
