### ISSUE TITLE
"Environments" for both Kubeflow model workflows and KFServing to better manage dependencies

### ISSUE THREAD

**Issue by jpatanooga** [kubeflow/kfserving#835]
/kind feature

**Describe the solution you'd like**

A way to create an "environment" that contains a list of dependencies needed to:

1. train a model
2. serve inference from kfserving

This environment would work similarly to Anaconda's concept of environments such that each user could have their own separate set of different environments. These environments would also be referenceable by a yaml file to create an InferenceService object in KFServing such that a container could be generated automatically to have the correct set of dependencies to serve inferences

see also, "automatic container generation": https://github.com/kubeflow/kfserving/issues/830

In this case, the environment would exist as a saved resource and would be referenceable from the yaml, such as:

```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "sklearn-iris-gs"
spec:
  default:
    predictor:
      minReplicas: 1
      **environment: jp_sklearn_iris**
      sklearn:
        storageUri: "gs://pct-tmp"
```

The concept of referenceable environments would reduce issues of reproducibility in workflows and issues around having to manually build custom model servers for specific dependency issues.
