### ISSUE TITLE
storage-initializer container fails to download model from s3

### ISSUE THREAD

**Issue by fakeburst** [kubeflow/kfserving#849]
/kind bug

**What steps did you take and what happened:**

I've tried serving a model stored at s3 bucket following this guide: https://github.com/kubeflow/kfserving/tree/master/docs/samples/s3

Upon applying `InferenceService` manifest, container `storage-initializer` in pod `s3-predictor-default-xxxxx-deployment-xxxxxxx-xxxx` fails to start which in turn renders said `InferenceService` not ready

These are the logs of storage-initializer container
```sh
> kubectl logs s3-predictor-default-855rn-deployment-6d6864gnnvm storage-initializer
[I 200528 13:20:57 initializer-entrypoint:13] Initializing, args: src_uri [s3://kubeflow/flowers] dest_path[ [/mnt/models]
[I 200528 13:20:57 storage:35] Copying contents of s3://kubeflow/flowers to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 50, in download
    Storage._download_s3(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 65, in _download_s3
    client = Storage._create_minio_client()
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 217, in _create_minio_client
    secure=use_ssl)
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 150, in __init__
    is_valid_endpoint(endpoint)
  File "/usr/local/lib/python3.7/site-packages/minio/helpers.py", line 301, in is_valid_endpoint
    if hostname[-1] == '.':
IndexError: string index out of range
```

**What did you expect to happen:**

After applying `InferenceService` yaml, the model is successfully downloaded from s3 bucket and served.

**Anything else you would like to add:**

I've seen there was a PR recently that looks like to address this issue https://github.com/kubeflow/kfserving/pull/832, but I've also noticed that the values from Secret are passed to `kfserving-container` and not to `storage-initializer`
```yaml
> kubectl describe pod s3-predictor-default-hxb5w-deployment-6784b5c684-qmr2f
Name:           s3-predictor-default-hxb5w-deployment-6784b5c684-qmr2f
...
Init Containers:
  storage-initializer:
  ...
    Args:
      s3://kubeflow/flowers
      /mnt/models
    State:          Waiting
      Reason:       CrashLoopBackOff
  ...
Containers:
  kfserving-container:
   ...
    Environment:
      AWS_ACCESS_KEY_ID:      <set to the key 'awsAccessKeyID' in secret 'mysecret'>      Optional: false
      AWS_SECRET_ACCESS_KEY:  <set to the key 'awsSecretAccessKey' in secret 'mysecret'>  Optional: false
      S3_USE_HTTPS:           1
      S3_ENDPOINT:            s3.amazonaws.com.
      AWS_ENDPOINT_URL:       https://s3.amazonaws.com.
      AWS_REGION:             us-east-1
      S3_VERIFY_SSL:          1
      PORT:                   8080
      K_REVISION:             s3-predictor-default-hxb5w
      K_CONFIGURATION:        s3-predictor-default
      K_SERVICE:              s3-predictor-default
    ...
  queue-proxy:
   ...  
``` 

The manifest used
```yaml
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: s3
spec:
  default:
    predictor:
      serviceAccountName: sa
      tensorflow:
        storageUri: "s3://kubeflow/flowers"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    serving.kubeflow.org/s3-endpoint: s3.amazonaws.com.
    serving.kubeflow.org/s3-usehttps: "1" 
    serving.kubeflow.org/s3-verifyssl: "1"
    serving.kubeflow.org/s3-region: us-east-1
type: Opaque
stringData:
  awsAccessKeyID: xxxxx
  awsSecretAccessKey: xxxxx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
  - name: mysecret
```

**Environment:**

- Istio Version:
- Knative Version: v0.11.1 (knative kustomize folder taken from kubeflow 1.0.0)
- KFServing Version: 0.2.2 (kfserving kustomize folder taken from kubeflow 1.0.0)
- Kubeflow version: 1.0.2
- Kfdef: aws_cognito 
- Minikube version:
- Kubernetes version: (use `kubectl version`): Client Version: 1.18; Server Version: 1.14+
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@fakeburst it should gets injected to storage initializer too, check here.
https://github.com/kubeflow/kfserving/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L207

**Comment by yuzisun** [comment]
this should work, please reopen if still an issue for you.

/close

**Comment by Luke035** [comment]
I'm haiving the same issue here. 

These are my resources 
```
apiVersion: v1
kind: Secret
metadata:
  name: s3-mysecret
  namespace: test-kfserving
  annotations:
     serving.kubeflow.org/s3-endpoint: s3.amazonaws.com. # replace with your s3 endpoint
     serving.kubeflow.org/s3-usehttps: "1" # by default 1, for testing with minio you need to set to 0
type: Opaque
data:
  AWS_ACCESS_KEY_ID: REDACTED
  AWS_SECRET_ACCESS_KEY: REDACTED
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-personal-credentials
  namespace: test-kfserving
secrets:
  - name: s3-mysecret
```

... and InferenceService
```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: test-kfserving
spec:
  default:
    predictor:
      serviceAccountName: sa-personal-credentials
      #serviceAccountName: kfserving-s3-sa
      sklearn:
        storageUri: "REDACTED"
        runtimeVersion: 0.2.2
```

Logs are the same and I also noticed that env variable for S3 endpoints is not propagated

```
Init Containers:
  storage-initializer:
REDACTED
    Port:          <none>
    Host Port:     <none>
    Args:
      REDACTED
      /mnt/models
    State:          Terminated
      Reason:       Error
      Exit Code:    1
REDACTED
    Ready:          False
    Restart Count:  2
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /mnt/models from kfserving-provision-location (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from sa-personal-credentials-token-bwn69 (ro)
```

Any help would be really appreciated!

KF version 1.0.2
K8s version (EKS) 1.16
