### ISSUE TITLE
Using microk8s built-inregistry

### ISSUE THREAD

**Issue by celinew1221** [kubeflow/kfserving#857]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Is there a way to use microk8s built-in registry enabled by microk8s.enable registry, or any local private registry with KFServing?

The `10.152.183.15:5000` used below is my container-registry service's cluster IP and port.

I tried to create a secret using
```
# it's an insecure registry just for testing, so i'm using `dummy`
kubectl create secret `pod-registry` \
  --docker-server=10.152.183.15:5000 \
  --docker-email=dummy \
  --docker-username=dummy \
  --docker-password=dummy
```
then apply [custom hello world example](https://github.com/kubeflow/kfserving/tree/master/docs/samples/custom/hello-world)
```
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: custom-hello-world-flask
spec:
  default:
    predictor:
      custom:
        container:
          image: 10.152.183.15:5000/hello-world-flask:registry
          env:
            - name: GREETING_TARGET
              value: "Python KFServing Sample"
imagePullSecrets:
  - name: pod-registry
```

but when I check out the pod log:
`kubectl logs custom-hello-world-flask-predictor-default-9pvck-deploymenqvqc5 -n admin -c user-container`
it shows:
```
Error from server (BadRequest): container "user-container" in pod "custom-hello-world-flask-predictor-default-9pvck-deploymenqvqc5" is waiting to start: trying and failing to pull image
````

**What did you expect to happen:**
Pull from local private registry

**Environment:**
- KFServing Version: 0.2.2
- Kubeflow version: 1.0.0
- Kfdef:[k8s_istio]
- Microk8s version: 1.15
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS
