### ISSUE TITLE
[autoscaling] can not scale down the pod

### ISSUE THREAD

**Issue by edenbuaa** [kubeflow/kfserving#871]
**Environment:**

- Istio Version: 1.3.6
- Knative Version: v0.12.0
- KFServing Version: v0.3.0
- Kubernetes version: (use `kubectl version`): v1.15.1
- OS (e.g. from `/etc/os-release`): ubuntu

**What steps did you take and what happened:**

I have one node with 2 GPUs, and use the autoscalling case by the following yaml:

```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "pytorch-cifar10-gpu"
  autoscaling.knative.dev/target: "5"
spec:
  default:
    predictor:
      pytorch:
        storageUri: "pvc:/{pvc_name}/models/pytorch/cifar10/"
        modelClassName: "Net"
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
```
access the service by hey: 
`hey -z 30s -q 10 -m POST -host ${HOST} -D $INPUT_PATH `

the pods scale up to about 50, and most of them keep pending status all the time.

**What did you expect to happen:**

there are only 2 pod can be running, and it should scale down to 1 or 0 when the traffic is end.
