### ISSUE TITLE
Custom GPU inference image cannot auto scale across multi GPUs.

### ISSUE THREAD

**Issue by rtrobin** [kubeflow/kfserving#924]
/kind bug

**What steps did you take and what happened:**
I have a custom image which offers a prediction API. When I try [auto-scaling sample](https://github.com/kubeflow/kfserving/tree/master/docs/samples/autoscaling), all pods are attempting to allocate on the same GPU. Also most pods fail to launch and trigger restart.

**What did you expect to happen:**
Custom inference pods can auto scale across multi GPUs, like tf/pytorch pre-built predictor. 

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: 0.3
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@rtrobin Can you help elaborate how all pods can possibly allocate on the same GPU ? Can you paste the custom inference service yaml and what errors you saw?

**Comment by rtrobin** [comment]
@yuzisun Hi, I don't know the exact code implementation. The docker is shipped by other team, which provides a web service. The DL model is compiled from Tensorflow into dynamic library, called by main program. 

There are two errors in this case. First, not all pods are allocating on gpu worker nodes. Some pods applies on cpu worker node or even cpu master node. These pods fail to launch because no gpu card found, failed to load cudnn and other nvidia library. Second, I guess, the code loads TF model into default gpu device, which is No.0 card. I'm not sure how kfserving apply each pod on device. Maybe it needs to specify environment variable _CUDA_VISIBLE_DEVICES_ to restrict the devices that the pod could see.

My yaml file is shown below.

``` yaml
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: custom-service
spec:
  default:
    predictor:
      custom:
        container:
          image: custom-image
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
```
