### ISSUE TITLE
not able start kfserving with s3 

### ISSUE THREAD

**Issue by tiru1930** [kubeflow/kfserving#929]
/kind bug

Running kfserving with kubeflow installed on minkube for s3 tensorflow storage model  but awaiting at PodInitializing
```
kubectl get inferenceservice -n kfserving-test-2
NAME             URL                                                                           READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
effidet-s3                                                                                     False                                      83m
effidet-s3-1                                                                                   False                                      7m30s
flowers-sample   http://flowers-sample.kfserving-test-2.example.com/v1/models/flowers-sample   True    100                                109m
sklearn-iris     http://sklearn-iris.kfserving-test-2.example.com/v1/models/sklearn-iris       True    100                                17h

```
```
deployment.apps/effidet-s3-1-predictor-default-khtjq-deployment     0/0     0            0           6m45s
deployment.apps/effidet-s3-1-predictor-default-nc6kn-deployment     0/0     0            0           6m45s
replicaset.apps/effidet-s3-1-predictor-default-khtjq-deployment-55fc98844f    0         0         0       6m45s
replicaset.apps/effidet-s3-1-predictor-default-nc6kn-deployment-6dcfb7bf56    0         0         0       6m45s
revision.serving.knative.dev/effidet-s3-1-predictor-default-khtjq     effidet-s3-1-predictor-default     effidet-s3-1-predictor-default-khtjq     1            False   PodInitializing
revision.serving.knative.dev/effidet-s3-1-predictor-default-nc6kn     effidet-s3-1-predictor-default     effidet-s3-1-predictor-default-nc6kn     2            False   PodInitializing
configuration.serving.knative.dev/effidet-s3-1-predictor-default     effidet-s3-1-predictor-default-nc6kn                                              False   RevisionFailed
service.serving.knative.dev/effidet-s3-1-predictor-default     http://effidet-s3-1-predictor-default.kfserving-test-2.example.com     effidet-s3-1-predictor-default-nc6kn                                              False   RevisionMissing
route.serving.knative.dev/effidet-s3-1-predictor-default     http://effidet-s3-1-predictor-default.kfserving-test-2.example.com     False   RevisionMissing

```
```
      s3://bucket_name/savd_model
      /mnt/models
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 10 Jul 2020 08:04:58 +0000
      Finished:     Fri, 10 Jul 2020 08:05:00 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 10 Jul 2020 08:04:41 +0000
      Finished:     Fri, 10 Jul 2020 08:04:43 +0000
    Ready:          False
    Restart Count:  2
```

Deployment file :

```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "effidet-s3-1"
spec:
  default:
    predictor:
      serviceAccountName: sa
      tensorflow:
        storageUri: "s3://bucket/saved_model"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    serving.kubeflow.org/s3-endpoint: s3.amazonaws.com.
    serving.kubeflow.org/s3-usehttps: "1" 
    serving.kubeflow.org/s3-verifyssl: "1"
    serving.kubeflow.org/s3-region: us-east-1
type: Opaque
stringData:
  awsAccessKeyID: xxxx=
  awsSecretAccessKey: xxx==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
  - name: mysecret
```

**Environment:**

- Kubeflow version: v1.0.2
- Minikube version: v1.8.0
- Kubernetes version: v1.17.3
- OS (e.g. from `/etc/os-release`):
