### ISSUE TITLE
How can we include post and pre process code inside the kfserving deployment?

### ISSUE THREAD

**Issue by tiru1930** [kubeflow/kfserving#940]
I am able to run one object detection solution using kf-serving, So here are my questions,

My solutions needs input images should be pre-processed and output detection should be post-processed which I can include in my graph,  so 

1. Is there any way that I can include my pre/post processing methods I can include inside my deployment so that I can have complete solutions in one deployment.

**Comment by yuzisun** [comment]
@tiru1930 Have you looked at the [transformer example](https://github.com/kubeflow/kfserving/tree/master/docs/samples/transformer/image_transformer) ?

**Comment by tiru1930** [comment]
@yuzisun yes, I have tried but , i am not seeing any , pod is terminating with no time, not able to storage container log, here is my deployment file

```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "effidet-s3-8"
  annotations:
    serving.kubeflow.org/s3-endpoint: s3.amazonaws.com
    serving.kubeflow.org/s3-usehttps: "1" 
    serving.kubeflow.org/s3-verifyssl: "1"
    serving.kubeflow.org/s3-region: us-east-1
spec:
  default:
    predictor:
      serviceAccountName: sa
      tensorflow:
        storageUri: "s3://bucketname/kf-serving/eff_savd_model"
  processer:
      custom:
        container:
          image: tiruai/effdetpro:latest
          name: user-container
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    serving.kubeflow.org/s3-endpoint: s3.amazonaws.com
    serving.kubeflow.org/s3-usehttps: "1" 
    serving.kubeflow.org/s3-verifyssl: "1"
    serving.kubeflow.org/s3-region: us-east-1
type: Opaque
stringData:
  awsAccessKeyID: xxxx
  awsSecretAccessKey: xxxx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
  - name: mysecret

```

**Comment by yuzisun** [comment]
@tiru1930 I think the spec is wrong, it should be something like this
```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "effidet-s3-8"
  annotations:
    serving.kubeflow.org/s3-endpoint: s3.amazonaws.com
    serving.kubeflow.org/s3-usehttps: "1" 
    serving.kubeflow.org/s3-verifyssl: "1"
    serving.kubeflow.org/s3-region: us-east-1
spec:
  default:
    predictor:
      serviceAccountName: sa
      tensorflow:
        storageUri: "s3://bucketname/kf-serving/eff_savd_model"
   transformer:
      custom:
        container:
          image: tiruai/effdetpro:latest
          name: user-container
```
